### ISSUE TITLE
Webcam example doesn't work on Windows

### ISSUE THREAD

**Issue by thewh1teagle** [aiortc/aiortc#1007]
I tried the webcam example which uses `av` (ffmpeg bindings) internally.
```
ffmpeg -y -f dshow -i video="HD camera " out.mp4
```shell
This command does work and capture my webcam

but when running the webcam example:
```shell
python webcam.py
```
with the following webcam name in code:
```python
  elif platform.system() == "Windows":
      webcam = MediaPlayer(
          "video=HD camera ", format="dshow", options=options
      )
```
I get this error:
```python
[dshow @ 000002667e9863c0] Could not set video options
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\aiortc\examples\webcam\webcam.py", line 78, in offer
    audio, video = create_local_tracks(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\aiortc\examples\webcam\webcam.py", line 35, in create_local_tracks
    webcam = MediaPlayer(
             ^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiortc\contrib\media.py", line 306, in __init__
    self.__container = av.open(
                       ^^^^^^^^
  File "av\\container\\core.pyx", line 401, in av.container.core.open
  File "av\\container\\core.pyx", line 265, in av.container.core.Container.__cinit__
  File "av\\container\\core.pyx", line 285, in av.container.core.Container.err_check
  File "av\\error.pyx", line 336, in av.error.err_check
av.error.OSError: [Errno 5] I/O error: 'video=HD camera '
INFO:aiohttp.access:127.0.0.1 [01/Dec/2023:13:38:17 +0000] "POST /offer HTTP/1.1" 500 245 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
INFO:aiohttp.access:127.0.0.1 [01/Dec/2023:13:38:19 +0000] "GET /v1/health HTTP/1.1" 404 173 "-" "undici"
INFO:aiohttp.access:127.0.0.1 [01/Dec/2023:13:38:49 +0000] "GET /v1/health HTTP/1.1" 404 173 "-" "undici"
```

**Comment by thewh1teagle** [comment]
when I removed the options it worked
