### ISSUE TITLE
Transport exceptions when client is disconnected unexpected (for example closing the browser tab)

### ISSUE THREAD

**Issue by el07694** [aiortc/aiortc#1040]
Hello there,

I am getting some errors while trying to close a browser tab when the connection is full established.
The example i am running is on [this repository](https://github.com/el07694/aiortc-demo-for-epalxeis).

How to go the error:
1. Run `python server_video.py`
2. Navigate to the ngrok url that ui of server_video.py provides in a QLineEdit.
3. Start a call from a browser.
4. Answer the call in pyqt5 app.
5. Close the browser tab
6. If the error doesn't happen in the console (server) after a few seconds repeat step 3-5 until reproduce.

Error message:
[
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\aiortc\rtcsctptransport.py", line 1339, in _send_chunk
    await self.__transport._send_data(
  File "C:\Python\Lib\site-packages\aiortc\rtcdtlstransport.py", line 578, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected

Task exception was never retrieved
future: <Task finished name='Task-2104' coro=<RTCSctpTransport._data_channel_flush() done, defined at C:\Python\Lib\site-packages\aiortc\rtcsctptransport.py:1646> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\aiortc\rtcsctptransport.py", line 1677, in _data_channel_flush
    await self._send(
  File "C:\Python\Lib\site-packages\aiortc\rtcsctptransport.py", line 1331, in _send
    await self._transmit()
  File "C:\Python\Lib\site-packages\aiortc\rtcsctptransport.py", line 1557, in _transmit
    await self._send_chunk(chunk)
  File "C:\Python\Lib\site-packages\aiortc\rtcsctptransport.py", line 1349, in _send_chunk
    raise e
  File "C:\Python\Lib\site-packages\aiortc\rtcsctptransport.py", line 1339, in _send_chunk
    await self.__transport._send_data(
  File "C:\Python\Lib\site-packages\aiortc\rtcdtlstransport.py", line 578, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\aiortc\rtcsctptransport.py", line 1339, in _send_chunk
    await self.__transport._send_data(
  File "C:\Python\Lib\site-packages\aiortc\rtcdtlstransport.py", line 578, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected](url)

What happens after that?

After that in some cases i cannot even revisit /index.html page.

How can i catch this errors and how can i resolve that?

**Comment by jlaine** [comment]
Can you please indicate whether you can reproduce this on one of the examples *we* provide? If it's reproducible with our code I'm happy to investigate, but I cannot go debugging third party code.

**Comment by el07694** [comment]
Ok, i will try to post tomorrow night

**Comment by el07694** [comment]
Ok after a few tries i can reproduce a almost same error with server example.
The only change i made i server example is in server.py file i replace the default ip from 0.0.0.0 to 192.168.1.188
Then i run the python server.py command, i open the browser and i navigated to http://192.168.1.188:8080, i select to send video from the checkbox and i push the start button. The connection was established well, i can't see and video element playing  but this is not the only error (the light in the client area camera is enabled). After that i open a second tab, i close the first one and here is the output from console:
```

======== Running on http://192.168.1.188:8080 ========
(Press CTRL+C to quit)
INFO:pc:PeerConnection(ddbcdb13-5698-4eb3-9f43-c6a5a02ef310) Created for 192.168.1.188
INFO:pc:PeerConnection(ddbcdb13-5698-4eb3-9f43-c6a5a02ef310) Track audio received
INFO:pc:PeerConnection(ddbcdb13-5698-4eb3-9f43-c6a5a02ef310) Track video received
INFO:aioice.ice:Connection(3) Could not bind to 169.254.119.55 - [WinError 10049] The requested address is not valid in its context
INFO:aioice.ice:Connection(3) Could not bind to 169.254.248.136 - [WinError 10049] The requested address is not valid in its context
INFO:aioice.ice:Connection(4) Could not bind to 169.254.119.55 - [WinError 10049] The requested address is not valid in its context
INFO:aioice.ice:Connection(4) Could not bind to 169.254.248.136 - [WinError 10049] The requested address is not valid in its context
INFO:aioice.ice:Connection(0) Could not bind to 169.254.119.55 - [WinError 10049] The requested address is not valid in its context
INFO:aioice.ice:Connection(0) Could not bind to 169.254.248.136 - [WinError 10049] The requested address is not valid in its context
INFO:aioice.ice:Connection(3) Could not bind to 169.254.144.162 - [WinError 10049] The requested address is not valid in its context
INFO:aioice.ice:Connection(4) Could not bind to 169.254.144.162 - [WinError 10049] The requested address is not valid in its context
INFO:aioice.ice:Connection(0) Could not bind to 169.254.144.162 - [WinError 10049] The requested address is not valid in its context
INFO:aioice.ice:Connection(0) Check CandidatePair(('2a02:587:4b08:7c00:d807:7791:5584:8e87', 58976) -> ('2a02:587:4b08:7c00:7523:c33b:cc49:66f9', 51182)) State.FROZEN -> State.WAITING
INFO:aioice.ice:Connection(0) Check CandidatePair(('2a02:587:4b08:7c00:7523:c33b:cc49:66f9', 58979) -> ('2a02:587:4b08:7c00:7523:c33b:cc49:66f9', 51182)) State.FROZEN -> State.WAITING
INFO:aioice.ice:Connection(0) Check CandidatePair(('2a02:587:4b2a:9700:2edd:267f:a8c1:a4c0', 58982) -> ('2a02:587:4b08:7c00:7523:c33b:cc49:66f9', 51182)) State.FROZEN -> State.WAITING
INFO:aioice.ice:Connection(0) Check CandidatePair(('2a02:587:4b08:7c00:d807:7791:5584:8e87', 58976) -> ('2a02:587:4b08:7c00:d807:7791:5584:8e87', 51183)) State.FROZEN -> State.WAITING
INFO:aioice.ice:Connection(0) Check CandidatePair(('192.168.1.188', 58985) -> ('192.168.1.188', 51181)) State.FROZEN -> State.WAITING
INFO:pc:PeerConnection(ddbcdb13-5698-4eb3-9f43-c6a5a02ef310) Connection state is connecting
INFO:aioice.ice:Connection(0) Check CandidatePair(('2a02:587:4b08:7c00:d807:7791:5584:8e87', 58976) -> ('2a02:587:4b08:7c00:7523:c33b:cc49:66f9', 51182)) State.WAITING -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('2a02:587:4b08:7c00:7523:c33b:cc49:66f9', 58979) -> ('2a02:587:4b08:7c00:7523:c33b:cc49:66f9', 51182)) State.WAITING -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('2a02:587:4b2a:9700:2edd:267f:a8c1:a4c0', 58982) -> ('2a02:587:4b08:7c00:7523:c33b:cc49:66f9', 51182)) State.WAITING -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('2a02:587:4b08:7c00:d807:7791:5584:8e87', 58976) -> ('2a02:587:4b08:7c00:d807:7791:5584:8e87', 51183)) State.WAITING -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('192.168.1.188', 58985) -> ('192.168.1.188', 51181)) State.WAITING -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('192.168.1.188', 58985) -> ('192.168.1.188', 51181)) State.IN_PROGRESS -> State.SUCCEEDED
INFO:aioice.ice:Connection(0) Check CandidatePair(('2a02:587:4b08:7c00:7523:c33b:cc49:66f9', 58979) -> ('2a02:587:4b08:7c00:d807:7791:5584:8e87', 51183)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('2a02:587:4b2a:9700:2edd:267f:a8c1:a4c0', 58982) -> ('2a02:587:4b08:7c00:d807:7791:5584:8e87', 51183)) State.FROZEN -> State.FAILED
INFO:aioice.ice:Connection(0) ICE completed
INFO:aioice.ice:Connection(0) Check CandidatePair(('2a02:587:4b2a:9700:2edd:267f:a8c1:a4c0', 58982) -> ('2a02:587:4b08:7c00:d807:7791:5584:8e87', 51183)) State.FAILED -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('2a02:587:4b2a:9700:2edd:267f:a8c1:a4c0', 58982) -> ('2a02:587:4b08:7c00:d807:7791:5584:8e87', 51183)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Consent to send expired
INFO:pc:PeerConnection(ddbcdb13-5698-4eb3-9f43-c6a5a02ef310) Connection state is failed
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\aiortc\rtcsctptransport.py", line 1339, in _send_chunk
    await self.__transport._send_data(
  File "C:\Python\Lib\site-packages\aiortc\rtcdtlstransport.py", line 578, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected

INFO:pc:PeerConnection(ddbcdb13-5698-4eb3-9f43-c6a5a02ef310) Connection state is closed
```

The problem is related with the last lines: ConnectionError: Cannot send encrypted data, not connected

**Comment by el07694** [comment]
The `_send_chunk` method may be:

```
	async def _send_chunk(self, chunk: Chunk) -> None:
		"""
		Transmit a chunk (no bundling for now).
		"""
		self.__log_debug("> %s", chunk)
        if self.__transport._state != State.CONNECTED:
            await self.__transport._send_data(
                serialize_packet(
                    self._local_port,
                    self._remote_port,
                    self._remote_verification_tag,
                    chunk,
                )
            )
```

Am i right?

**Comment by el07694** [comment]
Any update?
