### ISSUE TITLE
'server' example failed when served in a remote machine

### ISSUE THREAD

**Issue by sylyt62** [aiortc/aiortc#1069]
Before filing an issue please verify the following:

* Check whether there is already an existing issue for the same topic.

I found some similar issues : https://github.com/aiortc/aiortc/issues/832
But still cannot figure out what's going on in my environment.

I'm trying the 'server' example, which is using python as server and js as client. It works fine in my local machine or when server and client are in the same network.

But it failed when I start the server in AWS, and request from my local machine. I did the following:

1. added STUN and TURN config in both client.js and server.py, https://github.com/aiortc/aiortc/blob/e9c13eab915ddc27f365356ed9ded0585b9a1bb7/examples/server/client.js#L19
https://github.com/aiortc/aiortc/blob/e9c13eab915ddc27f365356ed9ded0585b9a1bb7/examples/server/server.py#L106 
2. disabled the firewall of the server machine and my local machine
3. start the server: `python3 server.py --host 0.0.0.0 --port 9088 --cert-file cert.pem --key-file key.pem`
4. visit https://xx.xx.xx.xx:xxxx/, check 'Use datachannel', 'Use audio', 'Use video', and 'Use STUN server', and start

And the post request for the offer failed (500 Internal Server Error), log from python:

> ======== Running on https://0.0.0.0:9088 ========
(Press CTRL+C to quit)
INFO:pc:PeerConnection(5aaf7971-8430-4e9a-85a7-a652d1adb2bb) Created for 223.104.41.34
INFO:pc:PeerConnection(5aaf7971-8430-4e9a-85a7-a652d1adb2bb) Track audio received
INFO:pc:PeerConnection(5aaf7971-8430-4e9a-85a7-a652d1adb2bb) Track video received
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "server.py", line 175, in offer
    await pc.setLocalDescription(answer)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiortc/rtcpeerconnection.py", line 795, in setLocalDescription
    await self.__gather()
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiortc/rtcpeerconnection.py", line 1041, in __gather
    await asyncio.gather(*coros)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiortc/rtcicetransport.py", line 201, in gather
    await self._connection.gather_candidates()
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aioice/ice.py", line 454, in gather_candidates
    for candidates in await asyncio.gather(*coros):
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aioice/ice.py", line 940, in get_component_candidates
    _, protocol = await turn.create_turn_endpoint(
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aioice/turn.py", line 441, in create_turn_endpoint
    await turn_transport._connect()
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aioice/turn.py", line 390, in _connect
    self.__relayed_address = await self.__inner_protocol.connect()
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aioice/turn.py", line 123, in connect
    response, _ = await self.request_with_retry(request)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aioice/turn.py", line 243, in request_with_retry
    response, addr = await self.request(request)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aioice/turn.py", line 230, in request
    return await transaction.run()
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aioice/stun.py", line 302, in run
    return await self.__future
aioice.stun.TransactionTimeout: STUN transaction timed out

And if I delete the TURN servers from the config, the post request can be send, but the ICE connection is always failed, log from python:

> (Press CTRL+C to quit)
INFO:pc:PeerConnection(fa413ce6-4c79-4b89-ac6f-a128765b85b8) Created for 223.104.41.34
INFO:pc:PeerConnection(fa413ce6-4c79-4b89-ac6f-a128765b85b8) Track audio received
INFO:pc:PeerConnection(fa413ce6-4c79-4b89-ac6f-a128765b85b8) Track video received
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('2.0.0.1', 51160)) State.FROZEN -> State.WAITING
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('2.0.0.1', 51160)) State.FROZEN -> State.WAITING
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('2.0.0.1', 51160)) State.FROZEN -> State.WAITING
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('172.20.10.7', 51161)) State.FROZEN -> State.WAITING
INFO:pc:PeerConnection(fa413ce6-4c79-4b89-ac6f-a128765b85b8) Connection state is connecting
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('2.0.0.1', 51160)) State.WAITING -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('2.0.0.1', 51160)) State.WAITING -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('2.0.0.1', 51160)) State.WAITING -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('172.20.10.7', 51161)) State.WAITING -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('172.20.10.7', 51161)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('172.20.10.7', 51161)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('223.104.41.34', 55721)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('223.104.41.34', 55721)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('223.104.41.34', 55721)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('54.37.76.82', 62694)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('54.37.76.82', 62694)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('54.37.76.82', 62694)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 49803)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 49803)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 49803)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 37052)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 37052)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 37052)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 62025)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 62025)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 62025)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 61595)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 61595)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 61595)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 55409)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 55409)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 55409)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 42320)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 42320)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 42320)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 53946)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 53946)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 53946)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 64335)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 64335)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 64335)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('2.0.0.1', 51160)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('2.0.0.1', 51160)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('2.0.0.1', 51160)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('172.20.10.7', 51161)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('172.20.10.7', 51161)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('172.20.10.7', 51161)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('223.104.41.34', 55721)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('223.104.41.34', 55721)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('223.104.41.34', 55721)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('54.37.76.82', 62694)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('54.37.76.82', 62694)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('54.37.76.82', 62694)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 49803)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 49803)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 49803)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 37052)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 37052)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 37052)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 62025)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 62025)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 62025)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 61595)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 61595)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 61595)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 55409)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 55409)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 55409)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 42320)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 42320)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 42320)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 53946)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 53946)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 53946)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.31.9.83', 33837) -> ('104.167.196.56', 64335)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 34069) -> ('104.167.196.56', 64335)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.18.0.1', 34110) -> ('104.167.196.56', 64335)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) ICE failed
INFO:pc:PeerConnection(fa413ce6-4c79-4b89-ac6f-a128765b85b8) Connection state is failed
INFO:pc:PeerConnection(fa413ce6-4c79-4b89-ac6f-a128765b85b8) Connection state is closed

Is there anything steps missing?

**Comment by sylyt62** [comment]
I also tried using only javascript as server and client side, served the code in the remote AWS machine, and the ICE connection can be built successfully.

**Comment by sylyt62** [comment]
Finding a working turn server solved it.
