### ISSUE TITLE
 'RTCRtpSender' object has no attribute '_RTCRtpSender__encoder'

### ISSUE THREAD

**Issue by danyow-cheung** [aiortc/aiortc#1124]
I am running the `https://github.com/aiortc/aiortc/blob/a9449820f745e63316b57914b2f1fa7c07f54d9a/examples/webcam/webcam.py ` file , using the command 
```
python .\webcam.py  --play-from .\video\demo.mp4 
```
And I got this issue  below . This suitation is that when i loaded out the end of  the video and this error showed up , but no issue during the webcam stream 

```
WARNING:aiortc.rtcdtlstransport:RTCDtlsTransport(client) 
Traceback (most recent call last):
  File "E:\Code\another_venv_1010\lib\site-packages\aiortc\rtcdtlstransport.py", line 517, in __run
    await self._recv_next()
  File "E:\Code\another_venv_1010\lib\site-packages\aiortc\rtcdtlstransport.py", line 614, in _recv_next
    await self._handle_rtcp_data(data)
  File "E:\Code\another_venv_1010\lib\site-packages\aiortc\rtcdtlstransport.py", line 557, in _handle_rtcp_data
    await recipient._handle_rtcp_packet(packet)
  File "E:\Code\another_venv_1010\lib\site-packages\aiortc\rtcrtpsender.py", line 265, in _handle_rtcp_packet
    if self.__encoder != None  and hasattr(self.__encoder, "target_bitrate"):
AttributeError: 'RTCRtpSender' object has no attribute '_RTCRtpSender__encoder'
```

**Comment by namoshizun** [comment]
Same here!!! We are using V1.9.0 and encountering the same bug. It appears to happen when closing a connection.

**Comment by tim-win** [comment]
Also running into this. Love the library, may be able to help debug later- as it appears to happen during shutdown, I can work around it for the time being I think!

**Comment by rayate2410** [comment]
Facing the same issue. 
```python
WARNING:aiortc.rtcdtlstransport:RTCDtlsTransport(client) Traceback (most recent call last):
  File "/home/workspace/aiortc/examples/server/aiortc_venv/lib64/python3.11/site-packages/aiortc/rtcdtlstransport.py", line 517, in __run
    await self._recv_next()
  File "/home/workspace/aiortc/examples/server/aiortc_venv/lib64/python3.11/site-packages/aiortc/rtcdtlstransport.py", line 614, in _recv_next
    await self._handle_rtcp_data(data)
  File "/home/workspace/aiortc/examples/server/aiortc_venv/lib64/python3.11/site-packages/aiortc/rtcdtlstransport.py", line 557, in _handle_rtcp_data
    await recipient._handle_rtcp_packet(packet)
  File "/home/workspace/aiortc/examples/server/aiortc_venv/lib64/python3.11/site-packages/aiortc/rtcrtpsender.py", line 264, in _handle_rtcp_packet
    if self.__encoder and hasattr(self.__encoder, "target_bitrate"):
       ^^^^^^^^^^^^^^
AttributeError: 'RTCRtpSender' object has no attribute '_RTCRtpSender__encoder'

INFO:pc:PeerConnection(3395a728-f62a-4c6b-8bf5-8b59b939ece6) Connection state is closed
```

**Comment by dannykok** [comment]
Same problem when using MediaPlayer with a test.mp4 file:
```
player = MediaPlayer("test.mp4", loop=True)
pc.addTrack(player.video)
```
After the video complete, the player will loop even though loop is specified as True. From debug logs:
```
DEBUG: MediaPlayer(test.mp4) Stopping worker thread
DEBUG: RTCRtpSender(video) - RTP finished
```

**Comment by jlaine** [comment]
Could you try changing the `del self.__encoder` into `self.__encoder = None` in `rtcrtpsender.py` ?
