### ISSUE TITLE
First example script doesn't work

### ISSUE THREAD

**Issue by TheCommCraft** [aiortc/aiortc#1125]
The first example "datachannel-cli" doesn't work, if I try to execute it this happens:
```python
C:\Users\*****\AppData\Local\Programs\Python\Python312\Lib\site-packages\google_crc32c\__init__.py:29: RuntimeWarning: As the c extension couldn't be imported, `google-crc32c` is using a pure python implementation that is significantly slower. If possible, please configure a c build environment and compile the extension
  warnings.warn(_SLOW_CRC32C_WARNING, RuntimeWarning)
C:\Users\*****\Downloads\rtctest010724.py:117: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Exception in callback _ProactorReadPipeTransport._loop_reading()
handle: <Handle _ProactorReadPipeTransport._loop_reading()>
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 306, in _loop_reading
    self._read_fut = self._loop._proactor.recv_into(self._sock, self._data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 483, in recv_into
    self._register_with_iocp(conn)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 704, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 6] Das Handle ist ungültig

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 316, in _loop_reading
    self._fatal_error(exc, 'Fatal read error on pipe transport')
  File "C:\Users\*****\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 132, in _fatal_error
    self._force_close(exc)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 135, in _force_close
    if self._empty_waiter is not None and not self._empty_waiter.done():
       ^^^^^^^^^^^^^^^^^^
AttributeError: '_ProactorReadPipeTransport' object has no attribute '_empty_waiter'
```

**Comment by Changan-X** [comment]
I meet the same situation.

**Comment by ckbarrett** [comment]
Same here as well

**Comment by naruya** [comment]
same issue... 😭

**Comment by naruya** [comment]
The error is gone when I follow this.

https://github.com/aiortc/aiortc/issues/396#issuecomment-1153377202

and maybe I can confirm that it works by adding the `--verbose` option.

```
% python cli.py offer --signaling tcp-socket --verbose
% python cli.py answer --signaling tcp-socket --verbose
```


https://github.com/user-attachments/assets/06996ff0-455a-4034-9d9a-7cc215e5b1ee
