### ISSUE TITLE
Connection error when two browser peers are connected to one python user

### ISSUE THREAD

**Issue by el07694** [aiortc/aiortc#1133]
The error:

```
======== Running on http://192.168.1.10:8080 ========
(Press CTRL+C to quit)
Exception in callback Transaction.__retry()
handle: <TimerHandle when=12134.937 Transaction.__retry()>
Traceback (most recent call last):
  File "C:\Python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python\lib\site-packages\aioice\stun.py", line 309, in __retry
    self.__future.set_exception(TransactionTimeout())
asyncio.exceptions.InvalidStateError: invalid state
Task exception was never retrieved
future: <Task finished name='Task-27689' coro=<RTCSctpTransport._data_channel_flush() done, defined at C:\Python\lib\site-packages\aiortc\rtcsctptransport.py:1642> exception=ConnectionError('Cannot send data, not connected')>
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\aiortc\rtcsctptransport.py", line 1673, in _data_channel_flush
    await self._send(
  File "C:\Python\lib\site-packages\aiortc\rtcsctptransport.py", line 1330, in _send
    await self._transmit()
  File "C:\Python\lib\site-packages\aiortc\rtcsctptransport.py", line 1553, in _transmit
    await self._send_chunk(chunk)
  File "C:\Python\lib\site-packages\aiortc\rtcsctptransport.py", line 1337, in _send_chunk
    await self.__transport._send_data(
  File "C:\Python\lib\site-packages\aiortc\rtcdtlstransport.py", line 649, in _send_data
    await self._write_ssl()
  File "C:\Python\lib\site-packages\aiortc\rtcdtlstransport.py", line 691, in _write_ssl
    await self.transport._send(data)
  File "C:\Python\lib\site-packages\aioice\ice.py", line 604, in send
    await self.sendto(data, 1)
  File "C:\Python\lib\site-packages\aioice\ice.py", line 619, in sendto
    raise ConnectionError("Cannot send data, not connected")
ConnectionError: Cannot send data, not connected
```

When i connect the first browser peer everything seems to work ok.
But when i connect a second browser peer:

1. There is a big video/audio latency
2. After some seconds the up error happens and the connections are closed.

I don't use exactly 100% the code in one of the projects examples, but my code is based in the server example.

As for the first error this may be caused because i use my mobile phone as hotspot here in my village (i am on vacations) and the python server user is in another town. The second error also happened without using hotspot.

Can you please advice me with this error?

Note that i can give you some code if you ask.

**Comment by el07694** [comment]
Generally i have fixed the error.
For the full python app, now i have a cpu load of 23%.
I have no latency for three connections (maximum case).
I have no connections corruptions.
Finally i fixed!

Now the next step is to connect each pear each other by using the existing datachannels to transmit offers and answers from each peer using python user as signalling server (to transmit offers and answers to each peer).

Is this possible?
