### ISSUE TITLE
How can I connect my OpenCV videocapture to webrtc?

### ISSUE THREAD

**Issue by JeffNUCode** [aiortc/aiortc#147]
Hi I'm new to webrtc and aiortc I would like to know how to connect my OpenCV project to webrtc for live streaming. But  I don't know how to do that. 

This is my code

import cv2
import numpy as np

cap = cv2.VideoCapture(0)

currentFrame = 0
while(True):
     ret, frame = cap.read()

     frame = cv2.flip(frame,1)

     gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

     cv2.imshow('frame',gray)
     if cv2.waitKey(1) & 0xFF == ord('q'):
        break

     currentFrame += 1

cap.release()
cv2.destroyAllWindows()

**Comment by jlaine** [comment]
Hi!

I would suggest you do not use opencv's frame capture mechanism: it lacks timing information (when was the frame acquired?) and will block your event loop.

Instead you can use the MediaPlayer class (a wrapper around FFmpeg) provided with aiortc which supports video acquisition, as illustrated in this example:

https://github.com/aiortc/aiortc/tree/master/examples/webcam

**Comment by raghavendrajain** [comment]
@jlaine Hi. I am running server on digital ocean and it gives me the following error:

```
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
Cannot open video device /dev/video0: No such file or directory
Error handling request
Traceback (most recent call last):
  File "/home/aiortc/examples/server/venv/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/aiortc/examples/server/venv/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "webcam.py", line 49, in offer
    player = MediaPlayer("/dev/video0", format="v4l2", options=options)
  File "/home/aiortc/examples/server/venv/lib/python3.6/site-packages/aiortc/contrib/media.py", line 221, in __init__
    self.__container = av.open(file=file, format=format, mode="r", options=options)
  File "av/container/core.pyx", line 226, in av.container.core.open
  File "av/container/core.pyx", line 148, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 180, in av.container.core.Container.err_check
  File "av/utils.pyx", line 107, in av.utils.err_check
av.AVError: [Errno 2] No such file or directory: '/dev/video0' (16: video4linux2,v4l2)
^CICE connection state is closed
```

It seems this program expects the webcam to the server itself. How do I make it work with a remote server?

**Comment by jlaine** [comment]
Please do not hijack closed issues.
