### ISSUE TITLE
Using STUN and TURN Server at the same time

### ISSUE THREAD

**Issue by TanjaBayer** [aiortc/aiortc#232]
Hi, 

I am currently trying to define add a stun and a turn server to my configuration, but it seems like it is using only the turn server: 

```
pc = RTCPeerConnection(
        configuration=RTCConfiguration([
            RTCIceServer("stun:stun.l.google:19302"),
            RTCIceServer("turn:turnserver.cidaas.de:3478?transport=udp", "user", "pw"),
            ]))
```

When I am behind a firewall which is blocking the turn server ports I receive the following error:

```
Error handling request
Traceback (most recent call last):
  File "/home/tanja/venvs/cidaas/id-services-aggregator/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/tanja/venvs/cidaas/id-services-aggregator/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/tanja/git/cidaas/id-card-utility-backend/server.py", line 104, in offer
    await pc.setLocalDescription(answer)
  File "/home/tanja/venvs/cidaas/id-services-aggregator/lib/python3.7/site-packages/aiortc/rtcpeerconnection.py", line 666, in setLocalDescription
    await self.__gather()
  File "/home/tanja/venvs/cidaas/id-services-aggregator/lib/python3.7/site-packages/aiortc/rtcpeerconnection.py", line 865, in __gather
    await asyncio.gather(*coros)
  File "/home/tanja/venvs/cidaas/id-services-aggregator/lib/python3.7/site-packages/aiortc/rtcicetransport.py", line 174, in gather
    await self._connection.gather_candidates()
  File "/home/tanja/venvs/cidaas/id-services-aggregator/lib/python3.7/site-packages/aioice/ice.py", line 362, in gather_candidates
    addresses=addresses)
  File "/home/tanja/venvs/cidaas/id-services-aggregator/lib/python3.7/site-packages/aioice/ice.py", line 749, in get_component_candidates
    transport=self.turn_transport)
  File "/home/tanja/venvs/cidaas/id-services-aggregator/lib/python3.7/site-packages/aioice/turn.py", line 301, in create_turn_endpoint
    await transport._connect()
  File "/home/tanja/venvs/cidaas/id-services-aggregator/lib/python3.7/site-packages/aioice/turn.py", line 272, in _connect
    self.__relayed_address = await self.__inner_protocol.connect()
  File "/home/tanja/venvs/cidaas/id-services-aggregator/lib/python3.7/site-packages/aioice/turn.py", line 80, in connect
    response, _ = await self.request(request)
  File "/home/tanja/venvs/cidaas/id-services-aggregator/lib/python3.7/site-packages/aioice/turn.py", line 173, in request
    return await transaction.run()
  File "/home/tanja/venvs/cidaas/id-services-aggregator/lib/python3.7/site-packages/aioice/stun.py", line 250, in run
    return await self.__future
aioice.exceptions.TransactionTimeout: STUN transaction timed out
```

when using the following configuration it works:
```
pc = RTCPeerConnection(
        configuration=RTCConfiguration([
            RTCIceServer("stun:stun.l.google:19302"),
            ]))

```
But when I use a mobile device using the configuration from above (turn + stun) it works (as the turn server connection is not blocked)

Any idea why it is not possible to use either stun or turn server, depending on which one is possible to use. Or is that expected behavior, if yes, what is the purpos of allowing muliple Server configuration? Shouldn't it give some kind of warning, that stun will not be used?

Or am I missing out some important config parameters?

Best Regards, 
Tanja

**Comment by lgrahl** [comment]
Can you enable debug logging and post the logging output?

**Comment by TanjaBayer** [comment]
This is the output when the connection failes with turn and stun configured at the same time:
```
INFO:pc:PeerConnection(310d62d6-e264-45b5-a432-9a3d13ace797) Created for 127.0.0.1
DEBUG:ice:controlled - new -> closed
INFO:pc:PeerConnection(310d62d6-e264-45b5-a432-9a3d13ace797) Track video received
DEBUG:ice:Connection(0) protocol(0) connection_made(<_SelectorDatagramTransport fd=9 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(1) connection_made(<_SelectorDatagramTransport fd=10 read=idle write=<idle, bufsize=0>>)
DEBUG:turn:turn/udp connection_made(<_SelectorDatagramTransport fd=11 read=idle write=<idle, bufsize=0>>)
DEBUG:turn:turn/udp > ('turnserver.cidaas.de', 3478) Message(message_method=Method.ALLOCATE, message_class=Class.REQUEST, transaction_id=b'\x9d\x10S\xcc\x10\x97B1\x90?\x04\xfd')
DEBUG:turn:turn/udp > ('turnserver.cidaas.de', 3478) Message(message_method=Method.ALLOCATE, message_class=Class.REQUEST, transaction_id=b'\x9d\x10S\xcc\x10\x97B1\x90?\x04\xfd')
DEBUG:turn:turn/udp > ('turnserver.cidaas.de', 3478) Message(message_method=Method.ALLOCATE, message_class=Class.REQUEST, transaction_id=b'\x9d\x10S\xcc\x10\x97B1\x90?\x04\xfd')
DEBUG:turn:turn/udp > ('turnserver.cidaas.de', 3478) Message(message_method=Method.ALLOCATE, message_class=Class.REQUEST, transaction_id=b'\x9d\x10S\xcc\x10\x97B1\x90?\x04\xfd')
DEBUG:turn:turn/udp > ('turnserver.cidaas.de', 3478) Message(message_method=Method.ALLOCATE, message_class=Class.REQUEST, transaction_id=b'\x9d\x10S\xcc\x10\x97B1\x90?\x04\xfd')
DEBUG:turn:turn/udp > ('turnserver.cidaas.de', 3478) Message(message_method=Method.ALLOCATE, message_class=Class.REQUEST, transaction_id=b'\x9d\x10S\xcc\x10\x97B1\x90?\x04\xfd')
DEBUG:turn:turn/udp > ('turnserver.cidaas.de', 3478) Message(message_method=Method.ALLOCATE, message_class=Class.REQUEST, transaction_id=b'\x9d\x10S\xcc\x10\x97B1\x90?\x04\xfd')
ERROR:aiohttp.server:Error handling request
```
When only using the stun I get this output:
```
INFO:pc:PeerConnection(37390150-aee3-41db-b036-0dda55d9f917) Created for 127.0.0.1
DEBUG:ice:controlled - new -> closed
INFO:pc:PeerConnection(37390150-aee3-41db-b036-0dda55d9f917) Track video received
DEBUG:ice:Connection(0) protocol(0) connection_made(<_SelectorDatagramTransport fd=9 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(1) connection_made(<_SelectorDatagramTransport fd=10 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:controlled - new -> checking
```

And when switching to a network which allowes the turn connection I see that output:
```
INFO:pc:PeerConnection(93a6674e-37dd-4a06-8ee8-2f43fdd7fc45) Created for 127.0.0.1
DEBUG:ice:controlled - new -> closed
INFO:pc:PeerConnection(93a6674e-37dd-4a06-8ee8-2f43fdd7fc45) Track video received
DEBUG:ice:Connection(0) protocol(0) connection_made(<_SelectorDatagramTransport fd=9 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(1) connection_made(<_SelectorDatagramTransport fd=10 read=idle write=<idle, bufsize=0>>)
DEBUG:turn:turn/udp connection_made(<_SelectorDatagramTransport fd=11 read=idle write=<idle, bufsize=0>>)
DEBUG:turn:turn/udp > ('turnserver.cidaas.de', 3478) Message(message_method=Method.ALLOCATE, message_class=Class.REQUEST, transaction_id=b'\xb2\x89`\x1b\x85\x13\r\x83e\xcf\x16[')
DEBUG:turn:turn/udp < ('18.185.84.96', 3478) Message(message_method=Method.ALLOCATE, message_class=Class.ERROR, transaction_id=b'\xb2\x89`\x1b\x85\x13\r\x83e\xcf\x16[')
DEBUG:turn:turn/udp > ('turnserver.cidaas.de', 3478) Message(message_method=Method.ALLOCATE, message_class=Class.REQUEST, transaction_id=b'N2\xd6\xe1\x99\xcf\x8c<\xcb\xf0\x91\xc6')
DEBUG:turn:turn/udp < ('18.185.84.96', 3478) Message(message_method=Method.ALLOCATE, message_class=Class.RESPONSE, transaction_id=b'N2\xd6\xe1\x99\xcf\x8c<\xcb\xf0\x91\xc6')
INFO:turn:TURN allocation created ('172.31.16.8', 63788)
DEBUG:ice:Connection(0) protocol(2) connection_made(<aioice.turn.TurnTransport object at 0x7f789b5edb10>)
DEBUG:ice:controlled - new -> checking
```

Yes I know that a turn is normally also a stun server, and ours also has the stun option enabled, but for me the question is, shouldn't it be possible when adding the turn and stun server and not getting any response from turn, can't we fall back to stun (or use the turn stun functionallity)
Actually my first guess would be that the connection tries stun first and if that fails, tries to us turn. 

What are your thoughts on that? What is the idea of defining different ICEServer if only one is used?

**Comment by TanjaBayer** [comment]
I digged a bit deeper into the implementation, and I think the issue is actually in aioice lib. 
When a turn server is provided the ice always tries to create a turn_endpoint and if that failes, the whole ICE connection failes, when catching that error and continuing with the candidate pairs already added (the stun server) the connection can be established, so I am going to close this issue and will open a new one in aioice project, because I am not sure if just catching the error is really an appropriate way...

**Comment by lgrahl** [comment]
AFAIK, your assumption is correct. The way it's intended to work is that STUN and TURN are fanned out and anything that works is being used. However, most implementations I've seen make optimisations here and there to prevent too many candidates from being gathered. Failures should be propagated as part of an event (in the web API that is `onicecandidateerror`) but these aren't fatal and the ICE process should just continue.

> When a turn server is provided the ice always tries to create a turn_endpoint and if that failes, the whole ICE connection failes [...]

I would classify that as a bug. Since you already digged that deep, perhaps you can provide a PR. :slightly_smiling_face:
