### ISSUE TITLE
Error installing aiortc with poetry on MacOS under Python 3.7.3 virtual environment

### ISSUE THREAD

**Issue by pcgeek86** [aiortc/aiortc#241]
In my Python project, using poetry, I ran the following command:

```
poetry add aiortc
```

Here are the results:

```
Using version ^0.9.22 for aiortc

Updating dependencies
Resolving dependencies... (4.3s)

Writing lock file


Package operations: 11 installs, 0 updates, 0 removals

  - Installing pycparser (2.19)
  - Installing cffi (1.13.2)
  - Installing cryptography (2.8)
  - Installing netifaces (0.10.9)
  - Installing aioice (0.6.16)
  - Installing av (6.2.0)
  - Installing crc32c (2.0)
  - Installing pyee (6.0.0)
  - Installing pylibsrtp (0.6.4)
  - Installing pyopenssl (19.1.0)
  - Installing aiortc (0.9.22)

[EnvCommandError]
Command ['/Users/trevorsullivan/Library/Caches/pypoetry/virtualenvs/pyserver-ZCFRwMsq-py3.7/bin/pip', 'install', '--no-deps', 'aiortc==0.9.22'] errored with the following return code 1, and output: 
Collecting aiortc==0.9.22
  Downloading https://files.pythonhosted.org/packages/59/68/0661d0a33b4937ac63630776610d26d8e5303219e92e3b86a7859b9e5cc6/aiortc-0.9.22.tar.gz (1.1MB)
Installing collected packages: aiortc
  Running setup.py install for aiortc: started
    Running setup.py install for aiortc: finished with status 'error'
    Complete output from command /Users/trevorsullivan/Library/Caches/pypoetry/virtualenvs/pyserver-ZCFRwMsq-py3.7/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/fb/vmlc1t2146jfh68t5cyxlkzc0000gn/T/pip-install-j2zy_rw7/aiortc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/fb/vmlc1t2146jfh68t5cyxlkzc0000gn/T/pip-record-5qhzscan/install-record.txt --single-version-externally-managed --compile --install-headers /Users/trevorsullivan/Library/Caches/pypoetry/virtualenvs/pyserver-ZCFRwMsq-py3.7/include/site/python3.7/aiortc:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/rtcsctptransport.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/rtcconfiguration.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/rtcrtpparameters.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/rtcdtlstransport.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/rtcdatachannel.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/mediastreams.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/jitterbuffer.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/rtcrtpsender.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/events.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/rate.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/clock.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/rtcpeerconnection.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/rtcicetransport.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/rtcrtpreceiver.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/utils.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/stats.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/exceptions.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/sdp.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/rtcsessiondescription.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/rtp.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    copying aiortc/rtcrtptransceiver.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc
    creating build/lib.macosx-10.14-x86_64-3.7/aiortc/codecs
    copying aiortc/codecs/h264.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc/codecs
    copying aiortc/codecs/g711.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc/codecs
    copying aiortc/codecs/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc/codecs
    copying aiortc/codecs/opus.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc/codecs
    copying aiortc/codecs/vpx.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc/codecs
    creating build/lib.macosx-10.14-x86_64-3.7/aiortc/contrib
    copying aiortc/contrib/media.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc/contrib
    copying aiortc/contrib/signaling.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc/contrib
    copying aiortc/contrib/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/aiortc/contrib
    running build_ext
    generating cffi module 'build/temp.macosx-10.14-x86_64-3.7/aiortc.codecs._vpx.c'
    creating build/temp.macosx-10.14-x86_64-3.7
    generating cffi module 'build/temp.macosx-10.14-x86_64-3.7/aiortc.codecs._opus.c'
    building 'aiortc.codecs._opus' extension
    creating build/temp.macosx-10.14-x86_64-3.7/build
    creating build/temp.macosx-10.14-x86_64-3.7/build/temp.macosx-10.14-x86_64-3.7sroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/Headers -I/Users/trevorsullivan/Library/Caches/pypoetry/virtualenvs/pyserver-ZCFRwMsq-py3.7/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/include/python3.7m -c build/temp.macosx-10.14-x86_64-3.7/aiortc.codecs._opus.c -o build/temp.macosx-10.14-x86_64-3.7/build/temp.macosx-10.14-x86_64-3.7/aiortc.codecs._opus.o
    build/temp.macosx-10.14-x86_64-3.7/aiortc.codecs._opus.c:493:10: fatal error: 'opus/opus.h' file not found
    #include <opus/opus.h>
             ^~~~~~~~~~~~~
    1 error generated.
    error: command 'xcrun' failed with exit status 1
    
    ----------------------------------------
Command "/Users/trevorsullivan/Library/Caches/pypoetry/virtualenvs/pyserver-ZCFRwMsq-py3.7/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/fb/vmlc1t2146jfh68t5cyxlkzc0000gn/T/pip-install-j2zy_rw7/aiortc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/fb/vmlc1t2146jfh68t5cyxlkzc0000gn/T/pip-record-5qhzscan/install-record.txt --single-version-externally-managed --compile --install-headers /Users/trevorsullivan/Library/Caches/pypoetry/virtualenvs/pyserver-ZCFRwMsq-py3.7/include/site/python3.7/aiortc" failed with error code 1 in /private/var/folders/fb/vmlc1t2146jfh68t5cyxlkzc0000gn/T/pip-install-j2zy_rw7/aiortc/
You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I found a couple other semi-related issues, but they don't appear to be directly relevant to this specific issue.

https://github.com/aiortc/aiortc/issues/122
https://github.com/aiortc/aiortc/issues/50

**Question**: How can I successfully install aiortc using poetry?

**Comment by pcgeek86** [comment]
Here is some additional information. I used Mac Homebrew to validate that `opus` was already installed. I then located the `opus.h` file here:

```
➜  opus ls -lGa /usr/local/include/opus/
total 312
drwxr-xr-x  7 trevorsullivan  staff    224 Apr 12  2019 .
drwxr-xr-x  3 trevorsullivan  staff     96 Apr 12  2019 ..
-rw-r--r--  1 trevorsullivan  staff  48429 Apr 12  2019 opus.h
-rw-r--r--  1 trevorsullivan  staff  34903 Apr 12  2019 opus_defines.h
-rw-r--r--  1 trevorsullivan  staff  33539 Apr 12  2019 opus_multistream.h
-rw-r--r--  1 trevorsullivan  staff  28240 Apr 12  2019 opus_projection.h
-rw-r--r--  1 trevorsullivan  staff   5157 Apr 12  2019 opus_types.h
```

**Comment by jlaine** [comment]
I'm sorry, I don't have access to an OS X physical machine. The builds on the CI server work OK, so maybe you need to pass some CFLAGS for `/usr/local/include` to be picked up by your compiler.

**Comment by roman-verbit-ai** [comment]
This issue should not be closed, it's still happening for the new M1 Macs.

I got it to compile and install using this command:
```
pip3 install \ 
   --global-option=build_ext 
   --global-option="-I/opt/homebrew/Cellar/opus/1.3.1/include:/opt/homebrew/Cellar/libvpx/1.11.0/include" \
   --global-option="-L/opt/homebrew/Cellar/opus/1.3.1/lib:/opt/homebrew/Cellar/libvpx/1.11.0/lib" aiortc
```
This is basically pointing pip to the right `lib` and `include` paths which I found using `brew`.

But there is still some mismatch during runtime, when trying to do actually import objects from aiortc.
This is the output I get now:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/himmelroman/aiortc_test/WebRTCPeer.py", line 3, in <module>
    from aiortc import RTCPeerConnection, RTCConfiguration, MediaStreamTrack
  File "/Users/himmelroman/aiortc_test/venv/lib/python3.8/site-packages/aiortc/__init__.py", line 11, in <module>
    from .rtcdtlstransport import (
  File "/Users/himmelroman/aiortc_test/venv/lib/python3.8/site-packages/aiortc/rtcdtlstransport.py", line 12, in <module>
    import pylibsrtp
  File "/Users/himmelroman/aiortc_test/venv/lib/python3.8/site-packages/pylibsrtp/__init__.py", line 4, in <module>
    from ._binding import ffi, lib
ImportError: dlopen(/Users/himmelroman/aiortc_test/venv/lib/python3.8/site-packages/pylibsrtp/_binding.abi3.so, 0x0002): symbol not found in flat namespace '_srtp_add_stream'
```
I'm not an expert on linkage, but it looks like the the code was compiled against a version which is different to the one it's linking to. Judging by the words "symbol not found".
This could be introduced by me, due to the include/lib paths I fed to `pip` when installing.
But I'm not sure how to investigate which libs python is really loading in runtime and compare that to what the paths I provided.

Help would be appreciated!
