### ISSUE TITLE
record with MediaRecorder from janus h264 Stream Invalid data found when processing input; last error log: [h264] no frame!

### ISSUE THREAD

**Issue by arpu** [aiortc/aiortc#315]
Hello,

i try to record a h264 stream from janus-gateway (master version) 

after i get the video track  the encoder shows many 
```
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
non-existing PPS 17 referenced
decode_slice_header error
no frame!
failed to decode, skipping package: [Errno 1094995529] Invalid data found when processing input; last error log: [h264] no frame!
non-existing PPS 17 referenced
decode_slice_header error
no frame!
failed to decode, skipping package: [Errno 1094995529] Invalid data found when processing input; last error log: [h264] no frame!
non-existing PPS 17 referenced
decode_slice_header error
no frame!
failed to decode, skipping package: [Errno 1094995529] Invalid data found when processing input; last error log: [h264] no frame!
non-existing PPS 17 referenced
decode_slice_header error
no frame!
failed to decode, skipping package: [Errno 1094995529] Invalid data found when processing input; last error log: [h264] no frame!
non-existing PPS 17 referenced
decode_slice_header error
no frame!
failed to decode, skipping package: [Errno 1094995529] Invalid data found when processing input; last error log: [h264] no frame!

```
any hint how i can debug or fix this? 

Python 3.7.6
aiortc             0.9.26

**Comment by arpu** [comment]
looks like waiting some more time this errors go away

**Comment by jlaine** [comment]
These errors are not emitted by aiortc but by FFmpeg, so it looks like something is wrong with the media stream. Can you please give me a step by step description of how to reproduce this?

**Comment by arpu** [comment]
hi will do some more testing on this ( sorry for the noise here) 

if you are on gitter can send you the janus  and i can broadcast to the janus room 
to get the video data.

right now  the errors gos away after some time...

the frames i get from aiortc are h264 encoded?  so the reencoding with pyAv should not be needed maybe only remux in a new container?

**Comment by arpu** [comment]
first idea was using copy 

```self.__container.add_stream("copy") ```

but looks like PyAv does not know the copy 

```
Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...Error('copy')>) at /usr/local/lib/python3.7/site-packages/pyee/_asyncio.py:55
handle: <Handle AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...Error('copy')>) at /usr/local/lib/python3.7/site-packages/pyee/_asyncio.py:55>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/site-packages/pyee/_asyncio.py", line 62, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.7/site-packages/pyee/_base.py", line 111, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/usr/local/lib/python3.7/site-packages/pyee/_base.py", line 83, in _emit_handle_potential_error
    raise error
  File "janus_recorder.py", line 111, in on_track
    recorder.addTrack(track)
  File "/usr/local/lib64/python3.7/site-packages/aiortc-0.9.27-py3.7-linux-x86_64.egg/aiortc/contrib/media.py", line 354, in addTrack
    stream = self.__container.add_stream("copy", rate=30)
  File "av/container/output.pyx", line 63, in av.container.output.OutputContainer.add_stream
  File "av/codec/codec.pyx", line 187, in av.codec.codec.Codec.__cinit__
  File "av/codec/codec.pyx", line 196, in av.codec.codec.Codec._init
av.codec.codec.UnknownCodecError: copy
```

anyone an idea?

**Comment by arpu** [comment]
hmm would it make sense not to encode first the h264 and than encode it again to h264? 

```
ERROR:libav.h264:non-existing PPS 21 referenced
ERROR:libav.h264:decode_slice_header error
ERROR:libav.h264:no frame!
WARNING:codec.h264:failed to decode, skipping package: [Errno 1094995529] Invalid data found when processing input; last error log: [h264] no frame!
```

or i misunderstand this?

**Comment by jlaine** [comment]
Please stay focused on the original issue, how do I reproduce it?

**Comment by arpu** [comment]
1. install janus master with enabled video room 
2. use the screencast janus example und broadcast  to video room 1234 ( set the videocodec="h264" in the config for video room 
3. try to record the h264 with 
```

import argparse
import asyncio
import logging
import random
import string
import time

import aiohttp

from aiortc import RTCPeerConnection, RTCSessionDescription, VideoStreamTrack
from aiortc.contrib.media import MediaBlackhole, MediaPlayer, MediaRecorder
from aiortc import RTCConfiguration, RTCIceServer

def transaction_id():
    return "".join(random.choice(string.ascii_letters) for x in range(12))


class JanusPlugin:
    def __init__(self, session, url, plugin_id):
        self._queue = asyncio.Queue()
        self._session = session
        self._url = url + "/" + str(plugin_id)
        self.plugin_id = plugin_id

    async def send(self, payload):
        message = {"janus": "message", "transaction": transaction_id()}
        message.update(payload)
        async with self._session._http.post(self._url, json=message) as response:
            data = await response.json()
            assert data["janus"] == "ack"

        response = await self._queue.get()
        assert response["transaction"] == message["transaction"]
        return response


class JanusSession:
    def __init__(self, url):
        self._http = None
        self._poll_task = None
        self._plugins = {}
        self._root_url = url
        self._session_url = None

    async def attach(self, plugin):
        message = {"janus": "attach", "plugin": plugin, "transaction": transaction_id()}
        async with self._http.post(self._session_url, json=message) as response:
            data = await response.json()
            assert data["janus"] == "success"
            plugin_id = data["data"]["id"]
            plugin = JanusPlugin(self, self._session_url, plugin_id)
            self._plugins[plugin_id] = plugin
            return plugin

    async def create(self):
        self._http = aiohttp.ClientSession()
        message = {"janus": "create", "transaction": transaction_id()}
        async with self._http.post(self._root_url, json=message) as response:
            data = await response.json()
            assert data["janus"] == "success"
            session_id = data["data"]["id"]
            self._session_url = self._root_url + "/" + str(session_id)

        self._poll_task = asyncio.ensure_future(self._poll())

    async def destroy(self):
        if self._poll_task:
            self._poll_task.cancel()
            self._poll_task = None

        if self._session_url:
            message = {"janus": "destroy", "transaction": transaction_id()}
            async with self._http.post(self._session_url, json=message) as response:
                data = await response.json()
                assert data["janus"] == "success"
            self._session_url = None

        if self._http:
            await self._http.close()
            self._http = None

    async def _poll(self):
        while True:
            params = {"maxev": 1, "rid": int(time.time() * 1000)}
            async with self._http.get(self._session_url, params=params) as response:
                data = await response.json()
                if data["janus"] == "event":
                    plugin = self._plugins.get(data["sender"], None)
                    if plugin:
                        await plugin._queue.put(data)
                    else:
                        print(data)


async def subscribe(sub_id, room, recorder, session):
    plugin = await session.attach("janus.plugin.videoroom")
    pc = RTCPeerConnection(configuration=RTCConfiguration(
        iceServers=[RTCIceServer(
          urls=['stun:stun.l.google.com:19302'])]))

    @pc.on("track")
    async def on_track(track):
        print("Track %s received" % track.kind)
        print(track)
        if track.kind == 'video':
            recorder.addTrack(track)
        if track.kind == 'audio':
           recorder.addTrack(track)

    request = {
        "request" : "join",
        "ptype" : "subscriber",
        "room" : room,
        "feed" : sub_id,
    }

    response = await plugin.send(
        {
            "body": request,
        }
    )

    if response['plugindata']['data'].get("error"):
        print('** [subscribe] response error')
        return
    print("response join")
    print(response)
    await pc.setRemoteDescription(RTCSessionDescription(
        sdp=response["jsep"]["sdp"], type=response["jsep"]["type"]
    ))

    answer = await pc.createAnswer()
    print("answer")
    print(answer)
    await pc.setLocalDescription(answer)

    response = await plugin.send(
        {
            "body": {"request" : "start"},
            "jsep": {
                "sdp": pc.localDescription.sdp,
                "trickle": False,
                "type": pc.localDescription.type,
            }
        }
    )
    print(response)
    await recorder.start()


async def run(pc, player, recorder, room, session):
    await session.create()

    plugin = await session.attach("janus.plugin.videoroom")

    videoroom_response = await plugin.send(
        {
            "body": {
                "display": "aiortc",
                "ptype": "publisher",
                "request": "join",
                "room": room,
            }
        }
    )
    print(videoroom_response)
    # find out who else is in the room?
    publishers = videoroom_response['plugindata']['data']['publishers']
    for publisher in publishers:
        remote_id = publisher['id']
        remote_name = publisher['display']
        print('remote_id:', remote_id, 'name:', remote_name)

    # start recording from 1st remote_id participant
    if publishers != []:
        await subscribe(publishers[0]["id"], room, recorder, session)

    # exchange media for 10 minutes
    print(" media")
   # await asyncio.sleep(600)
    print("--Stopped 10 minutes limit--")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Janus")
    parser.add_argument("url", help="Janus root URL, e.g. http://localhost:8088/janus")
    parser.add_argument(
        "--room",
        type=int,
        default=1234,
        help="The video room ID to join (default: 1234).",
    ),
    parser.add_argument("--play-from", help="Read the media from a file and sent it to room."),
    parser.add_argument("--record-to", help="Write the media received to a device."),
    parser.add_argument("--verbose", "-v", action="count")
    args = parser.parse_args()

    if args.verbose:
        logging.basicConfig(level=logging.DEBUG)

    # create signaling and peer connection
    session = JanusSession(args.url)
    pc = RTCPeerConnection(configuration=RTCConfiguration(
        iceServers=[RTCIceServer(
          urls=['stun:stun.l.google.com:19302'])]))

    # create media source
    player = None

    # create media sink
    if args.record_to:
        print('Recording to: ', args.record_to)
        options={'video_size': '2560x1440'}
        recorder = MediaRecorder(args.record_to,None, options)
    else:
        recorder = MediaBlackhole()

    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(
            run(pc=pc, player=player, recorder=recorder, room=args.room, session=session)
        )
    except KeyboardInterrupt:
        pass
    finally:
        loop.run_until_complete(recorder.stop())
        loop.run_until_complete(pc.close())
        loop.run_until_complete(session.destroy())
```

**Comment by arpu** [comment]
and a longer log output: https://gist.github.com/arpu/58e57fa6d3e16d767425a74188ac1a3a

**Comment by jlaine** [comment]
I hadn't understood the error you encountered was not with one of `aiortc`'s examples but with a custom piece of code. I'll be honest, I don't see myself installing janus or debugging your custom code soon.

**Comment by arpu** [comment]
maybe i can workaround this to use the raw rtp packages? any example available for this?

**Comment by jlaine** [comment]
> maybe i can workaround this to use the raw rtp packages? any example available for this?

No there is no example for this.

I have updated the janus example to record the first participant's video similar to what you did, except I didn't break the code to publish our own video. I have run the example against the public Janus server and don't see the errors you reported.

=> I doubt this issue has any relationship to janus itself

**Comment by arpu** [comment]
awesome!  will try with online official janus server 
thx for your time and update the sample

**Comment by arpu** [comment]
what i remember the videoroom example worked just fine! but not the screencast example ( bigger resolution (2k)

**Comment by arpu** [comment]
tested with the videoroom example in janus, and the recording works perfect
```
<av.AudioFrame 0, pts=1962240, 960 samples at 48000Hz, stereo, s16 at 0x7ff6f05c96d0>
<av.VideoFrame #918, pts=3682980 yuv420p 640x480 at 0x7ff6f0f45590>

```

but still some errors on screencast example recording 

```
<av.VideoFrame #41, pts=2401920 yuv420p 2560x1440 at 0x7f4ea10679f0>
<av.AudioFrame 0, pts=1272000, 960 samples at 48000Hz, stereo, s16 at 0x7f4ea06eb6d0>
<av.AudioFrame 0, pts=1272960, 960 samples at 48000Hz, stereo, s16 at 0x7f4ea069e7d0>
<av.AudioFrame 0, pts=1273920, 960 samples at 48000Hz, stereo, s16 at 0x7f4ea069ec50>
<av.AudioFrame 0, pts=1274880, 960 samples at 48000Hz, stereo, s16 at 0x7f4ea06ebe50>
<av.AudioFrame 0, pts=1275840, 960 samples at 48000Hz, stereo, s16 at 0x7f4ea10306d0>
<av.AudioFrame 0, pts=1276800, 960 samples at 48000Hz, stereo, s16 at 0x7f4ea06ebe50>
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
non-existing PPS 50 referenced
decode_slice_header error
no frame!
failed to decode, skipping package: [Errno 1094995529] Invalid data found when processing input; last error log: [h264] no frame!
<av.AudioFrame 0, pts=1287360, 960 samples at 48000Hz, stereo, s16 at 0x7f4ea069ec50>
non-existing PPS 50 referenced

```

@jlaine anything i should debug? or more a janus bug/problem

**Comment by arpu** [comment]
output if i use libopenh264 as decoder

```
OpenH264] this = 0x0x7fc8e0003730, Warning:parse_nal(), no exist Sequence Parameter Sets ahead of sequence when try to decode NAL(type:1).
DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
Exchanging media
DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
[OpenH264] this = 0x0x7fc8e0003730, Warning:referencing pictures lost due frame gaps exist, prev_frame_num: 2, curr_frame_num: 5
DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
DecodeFrame failed
 (repeated 51 more times)
[OpenH264] this = 0x0x7fc8e0003730, Error:PPS id (37) is invalid, previous id (-1) error ignored (0)!
DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame failed
failed to decode, skipping package: [Errno 1313558101] Unknown error occurred; last error log: [libopenh264] DecodeFrame 

```

setting libopenh264 here https://github.com/aiortc/aiortc/blob/master/src/aiortc/codecs/h264.py#L102

**Comment by arpu** [comment]
i do not get the error on the official janus installation ( online server) 
 the last change what i found is https://github.com/meetecho/janus-gateway/commit/5680b403223f7216789ea5149b0907ff2ba2726d

**Comment by arpu** [comment]
ok reverting this on janus server fixed the problem

**Comment by arpu** [comment]
one more note the official online janus server  use vp8 codec as default so there are no decode h264 errors

**Comment by arpu** [comment]
latest janus  master looks good now but  after
```[1499606792219112] Sent NACKs for 2 missing packets (video stream #0)```
in the janus log  aiortc does not show any new frames  any idea?

**Comment by arpu** [comment]
![Bildschirmfoto von 2020-03-24 23-01-18](https://user-images.githubusercontent.com/14173/77481190-6ecc1280-6e23-11ea-9079-65cedbc32825.png)

looks like this is happen if packetsSent/s is low

**Comment by arpu** [comment]
@jlaine  should i open a new issue on this?

**Comment by arpu** [comment]
the config is screen sharing with h264 and  yuv420p 1920x1080

**Comment by arpu** [comment]
can reproduce the problem and it always stops when [1391656481397027] Retransmitted 15 packets due to NACK (video stream #0)  comes in the janus log, does this helps?

**Comment by zh-nj** [comment]
same question，anyone help please！

**Comment by ntzagkarakiswings** [comment]
Any updates on this? same issue here. Recording VP8 from Janus is ok, but with h264 i get the same error

**Comment by anywo** [comment]
> the config is screen sharing with h264 and yuv420p 1920x1080

1920x1080 error!
1280x720 no problem!
