### ISSUE TITLE
janus vp9  ValueError: ICE username fragment or password is missing

### ISSUE THREAD

**Issue by arpu** [aiortc/aiortc#320]
get some strange error if i set the video_codec to vp9 in janus videoroom 

```
Traceback (most recent call last):
  File "janus.py", line 249, in <module>
    run(player=player, recorder=recorder, room=args.room, session=session)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "janus.py", line 201, in run
    await publish(plugin=plugin, player=player)
  File "janus.py", line 136, in publish
    sdp=response["jsep"]["sdp"], type=response["jsep"]["type"]
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcpeerconnection.py", line 754, in setRemoteDescription
    self.__validate_description(description, is_local=False)
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcpeerconnection.py", line 1121, in __validate_description
    raise ValueError("ICE username fragment or password is missing")
ValueError: ICE username fragment or password is missing
```

**Comment by arpu** [comment]
ah now i see this is the video publishing with h264
