### ISSUE TITLE
ValueError: packet is too long

### ISSUE THREAD

**Issue by arpu** [aiortc/aiortc#321]
after some time receiving vp8 video frame i get this error 

```
<av.VideoFrame #0, pts=4206510 yuv420p 2560x1440 at 0x7f2ed410a180>
<av.VideoFrame #0, pts=4209480 yuv420p 2560x1440 at 0x7f2ed4058800>
<av.VideoFrame #0, pts=4236570 yuv420p 2560x1440 at 0x7f2ed410a180>
client Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcdtlstransport.py", line 527, in __run
    await self._recv_next()
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcdtlstransport.py", line 626, in _recv_next
    await self._handle_rtp_data(data, arrival_time_ms=arrival_time_ms)
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcdtlstransport.py", line 579, in _handle_rtp_data
    await receiver._handle_rtp_packet(packet, arrival_time_ms=arrival_time_ms)
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcrtpreceiver.py", line 476, in _handle_rtp_packet
    packet.ssrc, sorted(self.__nack_generator.missing)
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcrtpreceiver.py", line 557, in _send_rtcp_nack
    await self._send_rtcp(packet)
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcrtpreceiver.py", line 544, in _send_rtcp
    await self.transport._send_rtp(bytes(packet))
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcdtlstransport.py", line 665, in _send_rtp
    data = self._tx_srtp.protect_rtcp(data)
  File "/usr/local/lib/python3.6/dist-packages/pylibsrtp-0.6.5-py3.6-linux-x86_64.egg/pylibsrtp/__init__.py", line 207, in protect_rtcp
    return self.__process(packet, lib.srtp_protect_rtcp, SRTP_MAX_TRAILER_LEN)
  File "/usr/local/lib/python3.6/dist-packages/pylibsrtp-0.6.5-py3.6-linux-x86_64.egg/pylibsrtp/__init__.py", line 231, in __process
    raise ValueError("packet is too long")
ValueError: packet is too long

```

**Comment by arpu** [comment]
same with h264 codec after running a while

```
WARNING:dtls:client Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcdtlstransport.py", line 527, in __run
    await self._recv_next()
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcdtlstransport.py", line 626, in _recv_next
    await self._handle_rtp_data(data, arrival_time_ms=arrival_time_ms)
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcdtlstransport.py", line 579, in _handle_rtp_data
    await receiver._handle_rtp_packet(packet, arrival_time_ms=arrival_time_ms)
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcrtpreceiver.py", line 476, in _handle_rtp_packet
    packet.ssrc, sorted(self.__nack_generator.missing)
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcrtpreceiver.py", line 557, in _send_rtcp_nack
    await self._send_rtcp(packet)
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcrtpreceiver.py", line 544, in _send_rtcp
    await self.transport._send_rtp(bytes(packet))
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcdtlstransport.py", line 665, in _send_rtp
    data = self._tx_srtp.protect_rtcp(data)
  File "/usr/local/lib/python3.6/dist-packages/pylibsrtp-0.6.5-py3.6-linux-x86_64.egg/pylibsrtp/__init__.py", line 207, in protect_rtcp
    return self.__process(packet, lib.srtp_protect_rtcp, SRTP_MAX_TRAILER_LEN)
  File "/usr/local/lib/python3.6/dist-packages/pylibsrtp-0.6.5-py3.6-linux-x86_64.egg/pylibsrtp/__init__.py", line 231, in __process
    raise ValueError("packet is too long")
ValueError: packet is too long

```

**Comment by arpu** [comment]
sorry for the noise it looks like this only happens if i set the video frame size wrong
