### ISSUE TITLE
VP9 receive setRemoteDescription error

### ISSUE THREAD

**Issue by arpu** [aiortc/aiortc#322]
when i receive vp9 codec i get this problem 
sdp is 
```
v=0
o=- 1583961806678409 1 IN IP4 51.158.174.83
s=VideoRoom 1234
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS janus
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 51.158.174.83
a=sendonly
a=mid:audio
a=rtcp-mux
a=ice-ufrag:/NO2
a=ice-pwd:ymDvWuWJ53SKAe8O2pKZnR
a=ice-options:trickle
a=fingerprint:sha-256 AE:C3:42:C1:9B:33:12:4F:60:68:F2:56:DE:B7:80:EE:D9:2E:F6:40:74:08:09:CF:49:D8:86:1F:F2:F5:12:FD
a=setup:actpass
a=rtpmap:111 opus/48000/2
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 urn:ietf:params:rtp-hdrext:sdes:mid
a=rtcp-fb:111 transport-cc
a=msid:janus janusa0
a=ssrc:4012372255 cname:janus
a=ssrc:4012372255 msid:janus janusa0
a=ssrc:4012372255 mslabel:janus
a=ssrc:4012372255 label:janusa0
a=candidate:1 1 udp 2013266431 10.6.0.169 39404 typ host
a=candidate:2 1 udp 1677722111 51.158.174.83 39404 typ srflx raddr 10.6.0.169 rport 39404
a=end-of-candidates
m=video 9 UDP/TLS/RTP/SAVPF 101 102
c=IN IP4 51.158.174.83
a=sendonly
a=mid:video
a=rtcp-mux
a=ice-ufrag:/NO2
a=ice-pwd:ymDvWuWJ53SKAe8O2pKZnR
a=ice-options:trickle
a=fingerprint:sha-256 AE:C3:42:C1:9B:33:12:4F:60:68:F2:56:DE:B7:80:EE:D9:2E:F6:40:74:08:09:CF:49:D8:86:1F:F2:F5:12:FD
a=setup:actpass
a=rtpmap:101 VP9/90000
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=extmap:2 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:13 urn:3gpp:video-orientation
a=rtpmap:102 rtx/90000
a=fmtp:102 apt=101
a=ssrc-group:FID 2454345973 2640153036
a=msid:janus janusv0
a=ssrc:2454345973 cname:janus
a=ssrc:2454345973 msid:janus janusv0
a=ssrc:2454345973 mslabel:janus
a=ssrc:2454345973 label:janusv0
a=ssrc:2640153036 cname:janus
a=ssrc:2640153036 msid:janus janusv0
a=ssrc:2640153036 mslabel:janus
a=ssrc:2640153036 label:janusv0
a=candidate:1 1 udp 2013266431 10.6.0.169 39404 typ host
a=candidate:2 1 udp 1677722111 51.158.174.83 39404 typ srflx raddr 10.6.0.169 rport 39404
a=end-of-candidates
```

error:
```
Traceback (most recent call last):
  File "ps_janus.py", line 251, in <module>
    run(player=player, recorder=recorder, room=args.room, session=session)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "ps_janus.py", line 208, in run
    session=session, room=room, feed=publishers[0]["id"], recorder=recorder
  File "ps_janus.py", line 164, in subscribe
    sdp=response["jsep"]["sdp"], type=response["jsep"]["type"]
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.27-py3.6-linux-x86_64.egg/aiortc/rtcpeerconnection.py", line 780, in setRemoteDescription
    assert len(common)
AssertionError

```

**Comment by jlaine** [comment]
VP9 is not supported and it seems to be the only offered video codec. However I agree aiortc should produce a better exception maybe a ValueError

**Comment by arpu** [comment]
i add a Vp9Decoder with Pyav to the media.py  all looks fine but the encoder ( ffmpeg) 

```Bitstream not supported by this decoder```

**Comment by arpu** [comment]
any known Problem why aiortc not support Vp9 ?

**Comment by jlaine** [comment]
You need to implement VP9 descriptor parsing / serialization.

Also the CPU load for encoding is much higher than VP8, making it often impractical for realtime encoding.

**Comment by arpu** [comment]
since Intel Kabylake  there is GPU Hardware vp9 encoding  ( with VAAPI) this should not be a issue anymore

**Comment by jlaine** [comment]
Good for you, now all you need to do is write the code, unit tests and submit a PR.

**Comment by arpu** [comment]
yeahh hopefully i have time and the knowledge to do this

**Comment by jlaine** [comment]
The first step is to implement parsing / serialization of the VP9 payload descriptor:

https://tools.ietf.org/html/draft-ietf-payload-vp9-09

You can base the code and tests on what was done for VP8

**Comment by danielkoohmarey-bc** [comment]
Following up @arpu have you started this? I may try to implement.

**Comment by arpu** [comment]
@danielkoohmarey-bc  no, nothing started on this on my side.
