### ISSUE TITLE
Video device not released after failed ICE connection state

### ISSUE THREAD

**Issue by Kazhuu** [aiortc/aiortc#330]
Hi and thanks for the awesome library! Appreciated a lot!

I've been using this with Raspberry Pi and compatible Pi camera which is represented as v4l2 device under `/dev/video0` with MediaHelper class. In my case I need to be able to close connection and then be able to reconnect. However I run to issues when reconnecting. Sometimes I receive error message `Device or resource busy: '/dev/video0'`, and almost always `ioctl(vidioc_qbuf): bad file descriptor` with `Some buffers are still owned by the caller
on close.` Sometimes in rare cases I even get segmentation fault too and whole application crashes.

I'm calling [close()](https://github.com/aiortc/aiortc/blob/master/src/aiortc/rtcpeerconnection.py#L420) on PeerConnection. Then trying to connect with new totally new instance of PeerConnection. Even when I add sleep between these calls same error messages pop up. Do I need to call some other functions than close() or is the issue with my code?

**Comment by jlaine** [comment]
Hi! Can you reproduce this behaviour with one of the examples?

**Comment by Kazhuu** [comment]
I was able to partially get the results with webcam example using [these](https://github.com/Kazhuu/aiortc/compare/master...Kazhuu:cleaning-resources-on-close) changes. I just basically enable reconnecting.

This was tested on latest Raspian `Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux` on Pi 4 and Chrome browser `Version 80.0.3987.132` running on my Linux laptop on the same network. FFMPEG on Raspian gives following version print
```
ffmpeg version 4.1.4-1+rpt7~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)
```
This setup is hosting example web page on my local network.

With this setup when I press start on my browser to see the video and then stop it. Following lines are printed on console on Python side:
```
ICE connection state is checking
ICE connection state is completed
Some buffers are still owned by the caller on close.
ioctl(VIDIOC_QBUF): Bad file descriptor
```
It's still not the exact same I see on my project but almost the same. What I'm wondering is that when on browser JS is calling `close()` on its PeerConnection instance it doesn't invoke `iceconnectionstatechange` event on Python side. When I press CTRL+C on Python code I will see line `ICE connection state is closed` printed to console, meaning `iceconnectionstatechange` event was triggered. So when connection is closed on Python side I see `iceconnectionstatechange` event but not when browser peer is calling `close()`. Is this how WebRTC is supposed to work?

Also with above behavior if from browser I stop first video, then press start button again. Another video stream will start and then closing again by pressing stop. And now I terminate Python program with CTRL+C. I get following console print:
```
ICE connection state is checking
ICE connection state is completed
Some buffers are still owned by the caller on close.
ioctl(VIDIOC_QBUF): Bad file descriptor
ICE connection state is checking
ICE connection state is completed
Some buffers are still owned by the caller on close.
ioctl(VIDIOC_QBUF): Bad file descriptor
ICE connection state is closed
ICE connection state is closed
```
From above you also see that PeerConnection object on Python side is closed when its `close()` method is called on exit and not when JS is calling `PeerConnection.close()`. I was expecting to have `ICE connection state is closed` print between video streams not all at the end. Is this normal behavior?

**Comment by sy-eng** [comment]
Hi, 
I also have the same problem.
I want to check whether a light is controlled correctly with a webcam.
My OS is Ubuntu20.04.

I wrote some [codes](https://github.com/sy-eng/lightControl/tree/master), referring [aiortc/aiortc/examples/webcam](https://github.com/aiortc/aiortc/tree/master/examples/webcam).
When I run the codes, I found the errors shown below as  Kazhuu mentioned,
~~~
Some buffers are still owned by the caller on close.
ioctl(VIDIOC_QBUF): Bad file descriptor
~~~

Now, I add shutDown function in my webcam.py to call on_shutdown function,
which is called only on exiting webcam.py in  the original webcam.py, to release /dev/video0.

I guess the errors occurs in self.__container.close() in _stop() in MediaPlayer class in aiortc/contribute/media.py.
Now, I do not understand these codes well, but I guess to close the stream, some additional
processes might be required. (clearing __streams[]??? etc. ???)

I will test some modifications on media.py.

(Sorry my poor English)

**Comment by Kazhuu** [comment]
Those messages are coming from [libav](https://github.com/libav/libav/blob/master/libavdevice/v4l2.c#L885) it seems and I think they are pretty harmless.

Related to my earlier problem I think it's just how WebRTC is supposed to work. When JS client closes peer2peer connection it doesn't trigger connection change on the server right away. It will be triggered little bit later if you let it wait. I guess WebRTC is trying to reconnect.

**Comment by sy-eng** [comment]
>It will be triggered little bit later if you let it wait. 
Do you mean JS client trigger "closed" signal not right away but little bit later?
I guess the closed signal triggered only when the python program is closed, because 
__updateIceConnectionState() in rtcpeerconnection.py checks only self.__isClosed variable and
the variable is only updated in close() in the python file.

To check rtcpeerconnection.py behavior, I modified the file:
~~~
    def __updateIceConnectionState(self) -> None:
        # compute new state
        states = set(map(lambda x: x.state, self.__iceTransports))
        if self.__isClosed:
            state = "closed"
        elif "failed" in states:
            state = "failed"
        elif states == set(["completed"]):
            state = "completed"
        elif "checking" in states:
            state = "checking"
        elif "closed" in states:
            print("closed!!!!!")
            state = "new"
        else:
            state = "new"
           
        print(str(states))
        print(self)

        # update state
        if state != self.__iceConnectionState:
            self.__iceConnectionState = state
            self.emit("iceconnectionstatechange")
~~~

And I got the result:
~~~
{'new'}
<aiortc.rtcpeerconnection.RTCPeerConnection object at 0x7f86200dab20>
{'new'}
<aiortc.rtcpeerconnection.RTCPeerConnection object at 0x7f86200dab20>
closed!!!!!
{'new', 'closed'}
<aiortc.rtcpeerconnection.RTCPeerConnection object at 0x7f86200dab20>
{'new'}
<aiortc.rtcpeerconnection.RTCPeerConnection object at 0x7f86200dab20>
{'checking'}
<aiortc.rtcpeerconnection.RTCPeerConnection object at 0x7f86200dab20>
ICE connection state is checking
{'completed'}
<aiortc.rtcpeerconnection.RTCPeerConnection object at 0x7f86200dab20>
ICE connection state is completed
Some buffers are still owned by the caller on close.
ioctl(VIDIOC_QBUF): Bad file descriptor
{'new'}
<aiortc.rtcpeerconnection.RTCPeerConnection object at 0x7f86200e73d0>
{'new'}
<aiortc.rtcpeerconnection.RTCPeerConnection object at 0x7f86200e73d0>
closed!!!!!
{'new', 'closed'}
<aiortc.rtcpeerconnection.RTCPeerConnection object at 0x7f86200e73d0>
{'new'}
<aiortc.rtcpeerconnection.RTCPeerConnection object at 0x7f86200e73d0>
{'checking'}
<aiortc.rtcpeerconnection.RTCPeerConnection object at 0x7f86200e73d0>
ICE connection state is checking
{'completed'}
<aiortc.rtcpeerconnection.RTCPeerConnection object at 0x7f86200e73d0>
ICE connection state is completed
~~~
As you know, when I pressed stop button on JS client side, I got the warning:
~~~
Some buffers are still owned by the caller on close.
ioctl(VIDIOC_QBUF): Bad file descriptor
~~~

I guess when the start button is pressed, new rtcpeerconnection instance is created,
but it is not released when the stop button is pressed.

**Comment by sy-eng** [comment]
I guess webcam.py is a program which can accept a client browser.
(Because MediaPlayer("/dev/video0", format="v4l2", options=options), for example,
can not be invoked from several instances at the same time)
So, pcs should be cleared before new pc is added.

~~~
async def offer(request):
    params = await request.json()
    offer = RTCSessionDescription(sdp=params["sdp"], type=params["type"])

    coros = [pc.close() for pc in pcs]
    await asyncio.gather(*coros)
    pcs.clear()

    pc = RTCPeerConnection()
    pcs.add(pc)
    
    @pc.on("iceconnectionstatechange")
    async def on_iceconnectionstatechange():
        print("ICE connection state is %s" % pc.iceConnectionState)
        if pc.iceConnectionState == "failed":
            await pc.close()
            pcs.discard(pc)

    # open media source
    if args.play_from:
        player = MediaPlayer(args.play_from)
    else:
        options = {"framerate": "30", "video_size": "640x480"}
        if platform.system() == "Darwin":
            player = MediaPlayer("default:none", format="avfoundation", options=options)
        else:
            player = MediaPlayer("/dev/video0", format="v4l2", options=options)
~~~

**Comment by jlaine** [comment]
OK this issue is starting to be such a jumble of comments I cannot make sense of it anymore and am close to closing it. Can the original poster please restate exactly what the problem is and how I can reproduce it on an *unmodified* aiortc. I'm not interested in solving problems in custom code, just aiortc.

**Comment by Kazhuu** [comment]
Hello and after working on the software I think I finally figured my problem out. The main problem is that when WebRTC video (MediaHelper with v4l2) peer to peer connection establish fails and I call peerConnection.disconnect() before WebRTC connection reports failed state change. Now after the disconnect() I try to create new PeerConnection object and create new MediaPlayer with v4l2 I get `Device or resource busy: '/dev/video0'` with exception stack trace and many other exceptions as well from inside the library. You see some of my code there as well but you should get the idea.
```python
future: <Task finished coro=<AsyncClient._handle_eio_message() done, defined at /home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/socketio/asyncio_client.py:444> exception=OSError(16, 'Device or resource busy', '/dev/video0') created at /home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/engineio/asyncio_client.py:146>
source_traceback: Object created at (most recent call last):
  File "src/main.py", line 129, in <module>
    asyncio.run(main(), debug=True)
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1767, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/engineio/asyncio_client.py", line 477, in _read_loop_polling
    await self._receive_packet(pkt)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/engineio/asyncio_client.py", line 345, in _receive_packet
    await self._trigger_event('message', pkt.data, run_async=True)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/engineio/asyncio_client.py", line 395, in _trigger_event
    *args)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/engineio/asyncio_client.py", line 146, in start_background_task
    return asyncio.ensure_future(target(*args, **kwargs))
Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/socketio/asyncio_client.py", line 461, in _handle_eio_message
    await self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/socketio/asyncio_client.py", line 331, in _handle_event
    r = await self._trigger_event(data[0], namespace, *data[1:])
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/socketio/asyncio_client.py", line 387, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "/home/pi/dev/panta-control/src/video_stream.py", line 104, in create_peer
    await self._create_peer_connection()
  File "/home/pi/dev/panta-control/src/video_stream.py", line 122, in _create_peer_connection
    self.player = hardware.get_media_player()
  File "/home/pi/dev/panta-control/src/hardware.py", line 43, in get_media_player
    mediaPlayer = MediaPlayer('/dev/video0', format='v4l2', options=options)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/aiortc/contrib/media.py", line 226, in __init__
    self.__container = av.open(file=file, format=format, mode="r", options=options)
  File "av/container/core.pyx", line 365, in av.container.core.open
  File "av/container/core.pyx", line 235, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 267, in av.container.core.Container.err_check
  File "av/error.pyx", line 341, in av.error.err_check
av.error.OSError: [Errno 16] Device or resource busy: '/dev/video0'
Exception in callback Transaction.__retry()
handle: <TimerHandle when=10979.038931732 Transaction.__retry() created at /home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/aioice/stun.py:305>
source_traceback: Object created at (most recent call last):
  File "src/main.py", line 129, in <module>
    asyncio.run(main(), debug=True)
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1767, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/aioice/stun.py", line 305, in __retry
    self.__timeout_handle = loop.call_later(self.__timeout_delay, self.__retry)
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 987, in sendto
    self._sock.sendto(data, addr)
AttributeError: 'NoneType' object has no attribute 'sendto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/aioice/stun.py", line 302, in __retry
    self.__protocol.send_stun(self.__request, self.__addr)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/aioice/ice.py", line 231, in send_stun
    self.transport.sendto(bytes(message), addr)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 996, in sendto
    exc, 'Fatal write error on datagram transport')
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 664, in _fatal_error
    self._loop.call_exception_handler({
AttributeError: 'NoneType' object has no attribute 'call_exception_handler'
Exception in callback Transaction.__retry()
handle: <TimerHandle when=10979.058042697 Transaction.__retry() created at /home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/aioice/stun.py:305>
source_traceback: Object created at (most recent call last):
  File "src/main.py", line 129, in <module>
    asyncio.run(main(), debug=True)
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1767, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/aioice/stun.py", line 305, in __retry
    self.__timeout_handle = loop.call_later(self.__timeout_delay, self.__retry)
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 987, in sendto
    self._sock.sendto(data, addr)
AttributeError: 'NoneType' object has no attribute 'sendto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/aioice/stun.py", line 302, in __retry
    self.__protocol.send_stun(self.__request, self.__addr)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/aioice/ice.py", line 231, in send_stun
    self.transport.sendto(bytes(message), addr)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 996, in sendto
    exc, 'Fatal write error on datagram transport')
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 664, in _fatal_error
    self._loop.call_exception_handler({
AttributeError: 'NoneType' object has no attribute 'call_exception_handler'
Exception in callback Transaction.__retry()
handle: <TimerHandle when=10979.079627001 Transaction.__retry() created at /home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/aioice/stun.py:305>
source_traceback: Object created at (most recent call last):
  File "src/main.py", line 129, in <module>
    asyncio.run(main(), debug=True)
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1767, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/aioice/stun.py", line 305, in __retry
    self.__timeout_handle = loop.call_later(self.__timeout_delay, self.__retry)
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 987, in sendto
    self._sock.sendto(data, addr)
AttributeError: 'NoneType' object has no attribute 'sendto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/aioice/stun.py", line 302, in __retry
    self.__protocol.send_stun(self.__request, self.__addr)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/aioice/ice.py", line 231, in send_stun
    self.transport.sendto(bytes(message), addr)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 996, in sendto
    exc, 'Fatal write error on datagram transport')
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 664, in _fatal_error
    self._loop.call_exception_handler({
AttributeError: 'NoneType' object has no attribute 'call_exception_handler'
exchanging WebRTC offers timed out
```
What I was able to gather so far is that when I create `MediaPlayer` with v4l2 device it's opened in `__init__()` and then closed in `_stop()`. But I noticed that `_stop()` is never called, neither `_start()` when WebRTC is not able to establish connection. So in other words device is opened but never closed. So I tried to add `mediaPlayer._MediaPlayer__container.close()` after calling disconnect() and connect again. This gets rid of the resource busy error but I still receive multiple NoneType errors like above. After trying to connect second time I get segmentation fault consistently and whole program crashes.

I was thinking making example of this but I don't know how I can make aiortc fail with WebRTC peer to peer connection and then call disconnect. In my own setup I'm using custom Android app which fails to connect WebRTC with mobile connection. So I cannot reproduce it easily. Hope this is helpful :)

**Comment by Kazhuu** [comment]
Any ideas how to solve this? Maybe I try to explain it more clearly what is the problem for me.

When video is created like this
```
peer_connection = RTCPeerConnection()
mediaPlayer = MediaPlayer('/dev/video0', format='v4l2', options=options)` 
peer_connection.addTrack(player.video)
...
# Do signaling and exchange offers
...
# Now WebRTC will start ICE connection and it's state is checking
await self.peer_connection.setRemoteDescription(answer)
```
Now if peer to peer connection establishing fails for some reason and ICE connection state is reported to be failed and then closed. After this I can call `peer_connection.close()` to make sure everything is closed. Then later in the program try to establish new WebRTC connection by creating new `RTCPeerConnection` object and adding same `MediaPlayer` as earlier. I'll get following stack trace:
```
source_traceback: Object created at (most recent call last):
  File "src/main.py", line 129, in <module>
    asyncio.run(main(), debug=True)
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1767, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/engineio/asyncio_client.py", line 477, in _read_loop_polling
    await self._receive_packet(pkt)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/engineio/asyncio_client.py", line 345, in _receive_packet
    await self._trigger_event('message', pkt.data, run_async=True)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/engineio/asyncio_client.py", line 395, in _trigger_event
    *args)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/engineio/asyncio_client.py", line 146, in start_background_task
    return asyncio.ensure_future(target(*args, **kwargs))
Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/socketio/asyncio_client.py", line 461, in _handle_eio_message
    await self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/socketio/asyncio_client.py", line 331, in _handle_event
    r = await self._trigger_event(data[0], namespace, *data[1:])
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/socketio/asyncio_client.py", line 387, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "/home/pi/dev/panta-control/src/video_stream.py", line 104, in create_peer
    self._create_peer_connection()
  File "/home/pi/dev/panta-control/src/video_stream.py", line 122, in _create_peer_connection
    player = hardware.get_media_player()
  File "/home/pi/dev/panta-control/src/hardware.py", line 43, in get_media_player
    mediaPlayer = MediaPlayer('/dev/video0', format='v4l2', options=options)
  File "/home/pi/.local/share/virtualenvs/panta-control-NE4VbD54/lib/python3.7/site-packages/aiortc/contrib/media.py", line 226, in __init__
    self.__container = av.open(file=file, format=format, mode="r", options=options)
  File "av/container/core.pyx", line 365, in av.container.core.open
  File "av/container/core.pyx", line 235, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 267, in av.container.core.Container.err_check
  File "av/error.pyx", line 341, in av.error.err_check
av.error.OSError: [Errno 16] Device or resource busy: '/dev/video0'
```
So the opened v4l2 device is never closed properly and I never cannot open it again without closing the program.

I checked the code in MediaHelper class and it seems [_stop()](https://github.com/aiortc/aiortc/blob/master/src/aiortc/contrib/media.py#L291) which closes the v4l2 device properly. But the problem is this function is never called if peer to peer connection fails to be established. I also tried to reuse old `RTCPeerConnection` object but opening it again after closed it raises exception that connection is closed.

Any ideas how solve this?

**Comment by Kazhuu** [comment]
Okay I figured out simple example how to reproduce this issue. To make ICE connection state fail for sure I will not exchange candidates with the other peer with this [(diff)](https://github.com/Kazhuu/aiortc/commit/69087c8b9bf5b4477d2661d47ab4d7edeb49fe4f). This causes connection state to fail for sure even in localhost. Originally this problem existed for me over my mobile connection because my ISP is using symmetric NAT for mobile networks.

So with this example after connection fails, refresh frontend app and try connecting again and python will print following:
```python
Error handling request
Traceback (most recent call last):
  File "/home/kazooie/.local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/kazooie/.local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "webcam.py", line 49, in offer
    player = MediaPlayer("/dev/video0", format="v4l2", options=options)
  File "/home/kazooie/.local/lib/python3.8/site-packages/aiortc/contrib/media.py", line 226, in __init__
    self.__container = av.open(file=file, format=format, mode="r", options=options)
  File "av/container/core.pyx", line 365, in av.container.core.open
  File "av/container/core.pyx", line 235, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 267, in av.container.core.Container.err_check
  File "av/error.pyx", line 341, in av.error.err_check
av.error.OSError: [Errno 16] Device or resource busy: '/dev/video0'
```
Possible to add stop method MediaHelper to close the video device even on failed ICE connection attempts?

**Comment by Kazhuu** [comment]
Any information why PR is closed and not commented why :/ Maybe something missing or I overlooked? I guess there is a reason to keep device open for later access for threads or similar?

**Comment by jlaine** [comment]
There have been a number of improvements to connection state tracking, would you mind checking whether this still occurs?
