### ISSUE TITLE
datachannel-cli answer signaling fails first time

### ISSUE THREAD

**Issue by SoundsSerious** [aiortc/aiortc#393]
Hi,

Running the datachannel-cli example and the answer process always seems to fail each time. Wondering why, and how to create a reliable connection.

```
python ./aiortc/examples/datachannel-cli/cli.py answer -s tcp-socket
Traceback (most recent call last):
  File "./aiortc/examples/datachannel-cli/cli.py", line 119, in <module>
    loop.run_until_complete(coro)
  File "/Users/kevinrussell/anaconda2/envs/py3/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "./aiortc/examples/datachannel-cli/cli.py", line 65, in run_answer
    await consume_signaling(pc, signaling)
  File "./aiortc/examples/datachannel-cli/cli.py", line 21, in consume_signaling
    obj = await signaling.receive()
  File "/Users/kevinrussell/anaconda2/envs/py3/lib/python3.7/site-packages/aiortc/contrib/signaling.py", line 195, in receive
    await self._connect(False)
  File "/Users/kevinrussell/anaconda2/envs/py3/lib/python3.7/site-packages/aiortc/contrib/signaling.py", line 181, in _connect
    host=self._host, port=self._port
  File "/Users/kevinrussell/anaconda2/envs/py3/lib/python3.7/asyncio/streams.py", line 77, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/Users/kevinrussell/anaconda2/envs/py3/lib/python3.7/asyncio/base_events.py", line 954, in create_connection
    raise exceptions[0]
  File "/Users/kevinrussell/anaconda2/envs/py3/lib/python3.7/asyncio/base_events.py", line 941, in create_connection
    await self.sock_connect(sock, address)
  File "/Users/kevinrussell/anaconda2/envs/py3/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
  File "/Users/kevinrussell/anaconda2/envs/py3/lib/python3.7/asyncio/selector_events.py", line 494, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 1234)
```

**Comment by SoundsSerious** [comment]
The very next connection attempt works fine.

**Comment by SoundsSerious** [comment]
Believe this is answered by this:

https://stackoverflow.com/questions/36342899/asyncio-ensure-future-vs-baseeventloop-create-task-vs-simple-coroutine/36415477#36415477
