### ISSUE TITLE
pip install fails on JetsonNano (ARM64 architecture on Ubuntu derivative)

### ISSUE THREAD

**Issue by seank-com** [aiortc/aiortc#395]
I don't know enough about Python packaging and there is no documentation on building aiortc locally, otherwise I would try to submit a pull request. Note: I'm running as root (in a docker container) so sudo is not required.

```bash
root@JetsonNano:~# pip3 install aiohttp aiortc
Collecting aiohttp
  Downloading https://files.pythonhosted.org/packages/c2/f7/f0ad3dbace4762fef5d80aa4124b41bf218e4c4dd6d387a86cede707d9a4/aiohttp-3.6.2-py3-none-any.whl (441kB)
    100% |################################| 450kB 52kB/s
Collecting aiortc
  Downloading https://files.pythonhosted.org/packages/1a/34/d9c8e19b4d5157721a5b77750116c6bb6355f1d85b92e7de491269b9ee51/aiortc-0.9.28.tar.gz (1.2MB)
    100% |################################| 1.2MB 25kB/s
    Complete output from command python setup.py egg_info:
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp5l4__eeh', '--quiet', 'cffi>=1.0.0']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4atzmnkp/aiortc/setup.py", line 60, in <module>
        install_requires=install_requires,
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 160, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 155, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 698, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp5l4__eeh', '--quiet', 'cffi>=1.0.0']' returned non-zero exit status 1.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4atzmnkp/aiortc/
```

**Comment by seank-com** [comment]
I found [incomplete docs for building from source](https://github.com/aiortc/aiortc#building-from-source) and a [previous issue with Jetson](https://github.com/aiortc/aiortc/issues/126). I installed all of the referenced libraries as well as ffmpeg as re-ran pip install with the same error.

I also googled 'building pip packages from source' and the [featured hit](https://dzone.com/articles/executable-package-pip-install) said I should run ```python setup.py bdist_wheel``` from the root of the repo, but I get exactly the same error.

```bash
root@JetsonNano:~/aiortc# python3 setup.py bdist_wheel
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/setuptools/installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp2l_wgcb8', '--quiet', 'cffi>=1.0.0']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    install_requires=install_requires,
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 160, in setup
    _install_setup_requires(attrs)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 155, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 698, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 754, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp2l_wgcb8', '--quiet', 'cffi>=1.0.0']' returned non-zero exit status 1.
```

**Comment by jlaine** [comment]
Try updating your pip version (`pip install pip`), you should not need to build `aiortc` from source, binary wheels are provided for most platforms.

As for "there is no documentation on building aiortc locally", check the README.
