### ISSUE TITLE
datachannel-cli signaling fails

### ISSUE THREAD

**Issue by WilliamLee1004** [aiortc/aiortc#396]
Hi,

Running the datachannel-cli example process always seems to fail each time. Wondering why, and how to create a reliable connection.

```
Exception in callback _ProactorReadPipeTransport._loop_reading()
handle: <Handle _ProactorReadPipeTransport._loop_reading()>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 299, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 32768)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 441, in recv
    self._register_with_iocp(conn)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 714, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 6]  Invalid control code。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 309, in _loop_reading
    self._fatal_error(exc, 'Fatal read error on pipe transport')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 131, in _fatal_error
    self._force_close(exc)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 134, in _force_close
    if self._empty_waiter is not None and not self._empty_waiter.done():
AttributeError: '_ProactorReadPipeTransport' object has no attribute '_empty_waiter'
channel(chat) - created by local party
-- Please send this message to the remote party --
{"sdp": "v=0\r\no=- 3804379590 3804379590 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic:WMS *\r\nm=application 65354 DTLS/SCTP 5000\r\nc=IN IP4 192.168.1.254\r\na=mid:0\r\na=sctpmap:5000 webrtc-datachannel 65535\r\na=max-message-size:65536\r\na=candidate:1aa729f427b35454657b79a9c9c99a3d 1 udp 2130706431 192.168.1.254 65354 typ host\r\na=candidate:6434a2077d4da05c32cf8be17b8a5846 1 udp 2130706431 192.168.2.254 65355 typ host\r\na=candidate:0bf85ab042877a571b9b62d5a3fc9ccd 1 udp 2130706431 10.10.217.189 65356 typ host\r\na=candidate:e0cf4a604042f2b1a596057cba9bda5c 1 udp 1694498815 163.18.21.225 65356 typ srflx raddr 10.10.217.189 rport 65356\r\na=end-of-candidates\r\na=ice-ufrag:osKl\r\na=ice-pwd:d8kV7eEZVWqUzjiSoO0NOt\r\na=fingerprint:sha-256 4C:1D:35:AA:9D:13:2B:71:13:8E:EF:7F:46:E0:8D:5C:0D:E5:4B:A8:6E:52:09:E5:22:6D:C8:2A:D9:1D:49:B6\r\na=setup:actpass\r\n", "type": "offer"}

-- Please enter a message from remote party --

```

**Comment by jlaine** [comment]
My guess is the Windows console has compatibility with Python, try using a different signaling method.

**Comment by msvargas** [comment]
@jlaine  Thanks that works for me!  If I can help to anybody:

` python cli.py offer --signaling tcp-socket`
