### ISSUE TITLE
apprtc example broken

### ISSUE THREAD

**Issue by DevinBayly** [aiortc/aiortc#406]
The script works up until the aiortc peer is supposed to join the room. This message is what I'm getting 

```
AppRTC room is 8152665571 https://appr.tc/r/8152665571
Track video received
Traceback (most recent call last):
  File "apprtc.py", line 125, in <module>
    loop.run_until_complete(
  File "/home/dev/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "apprtc.py", line 86, in run
    await pc.addIceCandidate(obj)
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by kpunekar** [comment]
I saw that too

**Comment by jlaine** [comment]
You seem to be using the examples from HEAD, with the `aiortc` code from an older version
