### ISSUE TITLE
"aiortc.exceptions.InvalidStateError: RTCIceTransport is closed" using aiortc in uvicorn/starlette app

### ISSUE THREAD

**Issue by joseph-long** [aiortc/aiortc#429]
I'm trying to adapt the webcam example to work in an app built with the [Starlette](https://github.com/encode/starlette) asyncio webframework. Minimal changes were required, but the resulting [webcam2.py](https://github.com/joseph-long/starlette-aiortc-example/blob/main/webcam2.py) produces an InvalidStateError when I try to set up a WebRTC connection.

```
$ uvicorn  webcam2:app
INFO:     Started server process [33835]
INFO:uvicorn.error:Started server process [33835]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:52002 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:52002 - "GET /client.js HTTP/1.1" 200 OK
{<aiortc.rtcpeerconnection.RTCPeerConnection object at 0x7f9c14c66c10>}
DEBUG:ice:controlled - new -> closed
DEBUG:ice:Connection(0) protocol(0) connection_made(<UDPTransport closed=False 0x7f9c14cfb7a0>)
DEBUG:ice:Connection(0) protocol(1) connection_made(<UDPTransport closed=False 0x7f9c14cfb870>)
DEBUG:ice:Connection(0) protocol(2) connection_made(<UDPTransport closed=False 0x7f9c14cfb6d0>)
DEBUG:ice:Connection(0) protocol(3) connection_made(<UDPTransport closed=False 0x7f9c14cfb940>)
DEBUG:ice:Connection(0) protocol(4) connection_made(<UDPTransport closed=False 0x7f9c14cfba10>)
DEBUG:ice:Connection(0) protocol(0) > ('74.125.197.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xd7\xb6}U(,\x86\xcen\x92\x17\x9c')
DEBUG:ice:Connection(0) protocol(3) > ('74.125.197.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xa0\x84\x85\x8d2\xc3o\x06\xd4\xdc\xd3{')
DEBUG:ice:Connection(0) protocol(4) > ('74.125.197.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xde\x87\x18N\xbc\xa9\x1f\xc8%4\xbc\xc7')
DEBUG:ice:Connection(0) protocol(3) connection_lost([Errno 65] No route to host)
DEBUG:ice:Connection(0) protocol(4) connection_lost([Errno 65] No route to host)
DEBUG:ice:Connection(0) protocol(0) < ('74.125.197.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\xd7\xb6}U(,\x86\xcen\x92\x17\x9c')
DEBUG:ice:Connection(0) protocol(3) > ('74.125.197.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xa0\x84\x85\x8d2\xc3o\x06\xd4\xdc\xd3{')
DEBUG:ice:Connection(0) protocol(4) > ('74.125.197.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xde\x87\x18N\xbc\xa9\x1f\xc8%4\xbc\xc7')
DEBUG:ice:Connection(0) protocol(3) > ('74.125.197.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xa0\x84\x85\x8d2\xc3o\x06\xd4\xdc\xd3{')
DEBUG:ice:Connection(0) protocol(4) > ('74.125.197.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xde\x87\x18N\xbc\xa9\x1f\xc8%4\xbc\xc7')
DEBUG:ice:Connection(0) protocol(3) > ('74.125.197.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xa0\x84\x85\x8d2\xc3o\x06\xd4\xdc\xd3{')
DEBUG:ice:Connection(0) protocol(4) > ('74.125.197.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xde\x87\x18N\xbc\xa9\x1f\xc8%4\xbc\xc7')
INFO:     127.0.0.1:52063 - "POST /offer HTTP/1.1" 200 OK
DEBUG:ice:controlled - new -> checking
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.113', 52948) -> ('67.1.30.246', 59035)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('172.28.128.1', 55153) -> ('67.1.30.246', 59035)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('169.254.0.1', 57743) -> ('67.1.30.246', 59035)) State.FROZEN -> State.WAITING
ICE connection state is checking
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.113', 52948) -> ('67.1.30.246', 59035)) State.WAITING -> State.IN_PROGRESS
DEBUG:ice:Connection(0) protocol(0) > ('67.1.30.246', 59035) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'.\xe3\xe5m\xce\x9ba`\xa5\xea\x0b\x12')
DEBUG:ice:Connection(0) protocol(1) < ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 59036) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'r\x93\xc1\xc5?\x19*\xf3n\x0f\xe0\xcf')
DEBUG:ice:Connection(0) protocol(1) > ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 59036) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'r\x93\xc1\xc5?\x19*\xf3n\x0f\xe0\xcf')
INFO:ice:Connection(0) Discovered peer reflexive candidate Candidate(PZj0IwsVNL 1 udp 1853817087 fd53:c25c:318f:0:e945:1e01:5d5f:c269 59036 typ prflx)
INFO:ice:Connection(0) Check CandidatePair(('fd53:c25c:318f:0:c35:a820:78d8:8e14', 52949) -> ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 59036)) State.WAITING -> State.IN_PROGRESS
DEBUG:ice:Connection(0) protocol(1) > ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 59036) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'V\xfa]\xc0\x06\xd3\x08h\xcbWP\x99')
DEBUG:ice:Connection(0) protocol(1) < ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 59036) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'V\xfa]\xc0\x06\xd3\x08h\xcbWP\x99')
INFO:ice:Connection(0) Check CandidatePair(('fd53:c25c:318f:0:c35:a820:78d8:8e14', 52949) -> ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 59036)) State.IN_PROGRESS -> State.SUCCEEDED
INFO:ice:Connection(0) Check CandidatePair(('172.28.128.1', 55153) -> ('67.1.30.246', 59035)) State.WAITING -> State.FAILED
INFO:ice:Connection(0) Check CandidatePair(('169.254.0.1', 57743) -> ('67.1.30.246', 59035)) State.WAITING -> State.FAILED
INFO:ice:Connection(0) ICE completed
DEBUG:ice:controlled - checking -> completed
DEBUG:dtls:client - State.NEW -> State.CONNECTING
ICE connection state is completed
DEBUG:ice:controlled - completed -> failed
ICE connection state is failed
DEBUG:dtls:client - DTLS shutdown complete
DEBUG:ice:controlled - failed -> closed
ICE connection state is closed
DEBUG:dtls:client x DTLS handshake failed (connection error)
DEBUG:dtls:client - State.CONNECTING -> State.FAILED
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<RTCPeerConnection.__connect() done, defined at /Users/josephlong/devel/aiortc/src/aiortc/rtcpeerconnection.py:912> exception=InvalidStateError('RTCIceTransport is closed')>
Traceback (most recent call last):
  File "/Users/josephlong/devel/aiortc/src/aiortc/rtcpeerconnection.py", line 920, in __connect
    await iceTransport.start(self.__remoteIce[transceiver])
  File "/Users/josephlong/devel/aiortc/src/aiortc/rtcicetransport.py", line 301, in start
    raise InvalidStateError("RTCIceTransport is closed")
aiortc.exceptions.InvalidStateError: RTCIceTransport is closed
DEBUG:ice:Connection(0) protocol(0) connection_lost(None)
DEBUG:ice:Connection(0) protocol(1) connection_lost(None)
DEBUG:ice:Connection(0) protocol(2) connection_lost(None)
```

**Comment by joseph-long** [comment]
Another data point: the `filexfer.py` example, which optionally uses uvloop, also fails:

```
$ python filexfer.py send foo.txt
-- Please send this message to the remote party --
{"sdp": "v=0\r\no=- 3813323569 3813323569 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic:WMS *\r\nm=application 54578 DTLS/SCTP 5000\r\nc=IN IP4 192.168.1.113\r\na=mid:0\r\na=sctpmap:5000 webrtc-datachannel 65535\r\na=max-message-size:65536\r\na=candidate:95d98a0508fa7c56188a3d6374656593 1 udp 2130706431 192.168.1.113 54578 typ host\r\na=candidate:461140bfa346d4450e83478955bd0457 1 udp 2130706431 fd53:c25c:318f:0:c35:a820:78d8:8e14 54579 typ host\r\na=candidate:a744f47eaaffa254d78cb140c64a24cb 1 udp 2130706431 fd53:c25c:318f:0:e945:1e01:5d5f:c269 54580 typ host\r\na=candidate:ccb9aae9fb943d32c290ef394970b7b2 1 udp 2130706431 172.28.128.1 58746 typ host\r\na=candidate:f28388eb73d82814725f2d815e070df9 1 udp 2130706431 169.254.0.1 62917 typ host\r\na=candidate:b481ef0f7207f6b8510987cac1cf66b5 1 udp 1694498815 67.1.30.246 54578 typ srflx raddr 192.168.1.113 rport 54578\r\na=end-of-candidates\r\na=ice-ufrag:qmff\r\na=ice-pwd:9G3cNbFIozs25lNUUGCN24\r\na=fingerprint:sha-256 26:63:10:66:69:26:DA:D2:66:7F:F3:6F:0D:CC:96:ED:43:F1:3B:9A:3C:2E:AF:9E:26:B2:AB:83:44:CA:79:5F\r\na=setup:actpass\r\n", "type": "offer"}
-- Please send this message to the remote party --
{"type": "bye"}

Traceback (most recent call last):
  File "filexfer.py", line 115, in <module>
    loop.run_until_complete(coro)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "filexfer.py", line 84, in run_offer
    await signaling.send(pc.localDescription)
  File "/Users/josephlong/devel/aiortc/src/aiortc/contrib/signaling.py", line 147, in send
    self._write_pipe.write(object_to_string(descr) + "\n")
BlockingIOError: [Errno 35] write could not complete without blocking
```

**Comment by jlaine** [comment]
You're changing too many things here for me to diagnose. How about you *only* change the event loop to `uvloop` and check what the behaviour is?

**Comment by jlaine** [comment]
I ported both the "webcam" and "server" examples to use starlette + uvicorn and I'm not seeing this: the behaviour is identical to when using aiohttp.

**Comment by joseph-long** [comment]
Unable to reproduce with the latest versions of everything, provided I launch with `uvicorn webcam2:app` instead of `python webcam2.py`. Not sure what changed aside from the mDNS ICE candidate support but it seems like I'm unstuck now!
