### ISSUE TITLE
Janus audiobridge packets sent before DTLS negotiation completed

### ISSUE THREAD

**Issue by JonathanXu1** [aiortc/aiortc#450]
I've been trying to adapt the [Janus Example](https://github.com/aiortc/aiortc/tree/main/examples/janus) to work with the [Audiobridge Plugin](https://janus.conf.meetecho.com/docs/audiobridge), and have been having issues streaming an audio file to a Janus server. Specifically, it seems that the aiortc client is streaming data before the DTLS connection properly connects. It looks like the RTCPeerConnection needs the MediaPlayer added as a track before it can create an offer. I'm at a loss for how to debug this, and I'm not sure how the RTCPeerConnection starts sending these packets in the first place.

If anyone has any suggestions that would be super appreciated!

Client console log:
```
create session
join room
check exists
ping
{'janus': 'message', 'transaction': 'FzMwSvPRoyhp', 'body': {'display': '["86655584392323072","Noisy","https://xms-dev-1251001060.cos.ap-guangzhou.myqcloud.com/x-project/user-upload-files/d42ca330d93d88e0e7c19e2b2fe42fb5.jpg"]', 'request': 'join', 'room': '190031821650526208'}}
pong
{'janus': 'event', 'session_id': 4766852630823728, 'transaction': 'FzMwSvPRoyhp', 'sender': 1638466597223897, 'plugindata': {'plugin': 'janus.plugin.audiobridge', 'data': {'audiobridge': 'joined', 'room': '190031821650526208', 'id': '6ec4e18b-a6ad-4483-b674-8d66c970e7fc', 'participants': []}}}
before publish
added audio track
session destroy
Traceback (most recent call last):
  File "player.py", line 246, in <module>
    loop.run_until_complete(
  File "C:\Users\jonat\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "player.py", line 209, in run
    await publish(plugin=plugin, player=player)
  File "player.py", line 128, in publish
    sender = pc.addTrack(player.audio)
AttributeError: 'NoneType' object has no attribute 'audio'

(env) C:\Users\jonat\Documents\Coding\noisy\fanbookPy>python player.py --room 190031821650526208 --play-from 78.opus http://rtctest.tensafe.net:8088/janus
create session
join room
check exists
ping
{'janus': 'message', 'transaction': 'mlfOrMfneYTb', 'body': {'display': '["86655584392323072","Noisy","https://xms-dev-1251001060.cos.ap-guangzhou.myqcloud.com/x-project/user-upload-files/d42ca330d93d88e0e7c19e2b2fe42fb5.jpg"]', 'request': 'join', 'room': '190031821650526208'}}
pong
{'janus': 'event', 'session_id': 7117244557671675, 'transaction': 'mlfOrMfneYTb', 'sender': 6789516588887611, 'plugindata': {'plugin': 'janus.plugin.audiobridge', 'data': {'audiobridge': 'joined', 'room': '190031821650526208', 'id': 'dcbbf452-31fa-4edf-8ecd-a1770213056b', 'participants': []}}}
before publish
added audio track
create offer
set local description
send sdp request
ping
{'janus': 'message', 'transaction': 'QUlWHMcYOVnE', 'body': {'request': 'configure', 'audio': True, 'video': False}, 'jsep': {'sdp': 'v=0\r\no=- 3819785295 3819785295 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic:WMS *\r\nm=audio 59471 UDP/TLS/RTP/SAVPF 96 0 8\r\nc=IN IP4 192.168.11.116\r\na=sendrecv\r\na=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=mid:0\r\na=msid:ac26e2a1-8307-4bdf-98dc-677d0c066b7c bcf9cd89-16e5-43e0-9272-8e5afd240c4f\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-mux\r\na=ssrc:1485338281 cname:621bbcff-ba99-4130-8d79-211aa52691d5\r\na=rtpmap:96 opus/48000/2\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=candidate:846ed8314672893129e581fe151842d4 1 udp 2130706431 192.168.11.116 59471 typ host\r\na=candidate:4ba014ee881993b88aebffd78daf137f 1 udp 2130706431 192.168.55.49 59472 typ host\r\na=candidate:a3f0fce3cf28e56742b99ca17209b812 1 udp 16777215 106.52.182.190 53235 typ relay raddr 192.168.11.116 rport 59473\r\na=end-of-candidates\r\na=ice-ufrag:ZeVk\r\na=ice-pwd:6fBCK4YLnrvmnb0ODocc5x\r\na=fingerprint:sha-256 58:4D:AC:EA:FE:39:EB:CF:4B:D3:64:59:02:18:AB:D0:E5:DE:A2:CA:1C:69:25:35:14:60:53:7B:9C:88:0B:2D\r\na=setup:actpass\r\n', 'trickle': False, 'type': 'offer'}}
pong
{'janus': 'event', 'session_id': 7117244557671675, 'transaction': 'QUlWHMcYOVnE', 'sender': 6789516588887611, 'plugindata': {'plugin': 'janus.plugin.audiobridge', 'data': {'audiobridge': 'event', 'result': 'ok'}}, 'jsep': {'type': 'answer', 'sdp': 'v=0\r\no=- 1610796497428226 1 IN IP4 106.52.182.190\r\ns=AudioBridge 190031821650526208\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS janus\r\nm=audio 9 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 106.52.182.190\r\na=sendrecv\r\na=mid:0\r\na=rtcp-mux\r\na=ice-ufrag:kz3M\r\na=ice-pwd:N+7Sm7FBXn9j1DrfnExdJM\r\na=ice-options:trickle\r\na=fingerprint:sha-256 06:42:E6:1E:62:3D:31:84:70:C2:7E:40:79:C8:69:B3:B1:D4:16:DE:61:FC:15:99:70:B8:E7:91:DB:87:4B:7F\r\na=setup:active\r\na=rtpmap:96 opus/48000/2\r\na=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=fmtp:96 maxplaybackrate=16000; stereo=0; 
sprop-stereo=0; useinbandfec=0\r\na=candidate:1 1 udp 2013266431 10.0.19.8 38632 typ host\r\na=candidate:2 1 udp 1677722111 106.52.182.190 38632 typ srflx raddr 10.0.19.8 rport 38632\r\na=candidate:3 1 udp 503316991 106.52.182.190 62712 typ relay raddr 10.0.19.8 rport 38632\r\na=msid:janus janusa0\r\na=ssrc:760481575 cname:janus\r\na=ssrc:760481575 msid:janus janusa0\r\na=ssrc:760481575 mslabel:janus\r\na=ssrc:760481575 label:janusa0\r\na=end-of-candidates\r\n'}}
set remote description
after publish
Exchanging media
Task exception was never retrieved
future: <Task finished name='Task-28' coro=<TurnClientMixin.send_data() done, defined at C:\Users\jonat\Documents\Coding\noisy\fanbookPy\env\lib\site-packages\aioice\turn.py:190> exception=TransactionFailed(Message(message_method=Method.CHANNEL_BIND, message_class=Class.ERROR, transaction_id=b'\xa3\xb8}\x0f,8\xe1\xff"\xaf\xd7F'))>    
Traceback (most recent call last):
  File "C:\Users\jonat\Documents\Coding\noisy\fanbookPy\env\lib\site-packages\aioice\turn.py", line 202, in send_data
    await self.channel_bind(channel, addr)
  File "C:\Users\jonat\Documents\Coding\noisy\fanbookPy\env\lib\site-packages\aioice\turn.py", line 70, in channel_bind
    await self.request(request)
  File "C:\Users\jonat\Documents\Coding\noisy\fanbookPy\env\lib\site-packages\aioice\turn.py", line 186, in request
    return await transaction.run()
  File "C:\Users\jonat\Documents\Coding\noisy\fanbookPy\env\lib\site-packages\aioice\stun.py", line 292, in run
    return await self.__future
aioice.stun.TransactionFailed: STUN transaction failed (400 - You cannot use the same peer with different channel number  )
```

Code:
```python
import argparse
import asyncio
import logging
import random
import string
import time

import aiohttp

from aiortc import RTCPeerConnection, RTCSessionDescription, VideoStreamTrack, RTCConfiguration, RTCIceServer
from aiortc.contrib.media import MediaPlayer, MediaRecorder

pcs = set()


def transaction_id():
    return "".join(random.choice(string.ascii_letters) for x in range(12))


class JanusPlugin:
    def __init__(self, session, url):
        self._queue = asyncio.Queue()
        self._session = session
        self._url = url

    async def send(self, payload):
        message = {"janus": "message", "transaction": transaction_id()}
        message.update(payload)
        async with self._session._http.post(self._url, json=message) as response:
            data = await response.json()
            assert data["janus"] == "ack"
        response = await self._queue.get()
        print("ping")
        print(message)
        print("pong")
        print(response)
        assert response["transaction"] == message["transaction"]
        return response

    async def post(self, payload): # does no check for ack response or wait for get request
        message = {"janus": "message", "transaction": transaction_id()}
        message.update(payload)
        async with self._session._http.post(self._url, json=message) as response:
            response = await response.json()
        print("ping")
        print(message)
        print("pong")
        print(response)
        assert response["transaction"] == response["transaction"]
        return response


class JanusSession:
    def __init__(self, url):
        self._http = None
        self._poll_task = None
        self._plugins = {}
        self._root_url = url
        self._session_url = None

    async def attach(self, plugin_name: str) -> JanusPlugin:
        message = {
            "janus": "attach",
            "plugin": plugin_name,
            "transaction": transaction_id(),
        }
        async with self._http.post(self._session_url, json=message) as response:
            data = await response.json()
            assert data["janus"] == "success"
            plugin_id = data["data"]["id"]
            plugin = JanusPlugin(self, self._session_url + "/" + str(plugin_id))
            self._plugins[plugin_id] = plugin
            return plugin

    async def create(self):
        self._http = aiohttp.ClientSession()
        message = {"janus": "create", "transaction": transaction_id()}
        async with self._http.post(self._root_url, json=message) as response:
            data = await response.json()
            assert data["janus"] == "success"
            session_id = data["data"]["id"]
            self._session_url = self._root_url + "/" + str(session_id)

        self._poll_task = asyncio.ensure_future(self._poll())

    async def destroy(self):
        if self._poll_task:
            self._poll_task.cancel()
            self._poll_task = None

        if self._session_url:
            message = {"janus": "destroy", "transaction": transaction_id()}
            async with self._http.post(self._session_url, json=message) as response:
                data = await response.json()
                assert data["janus"] == "success"
            self._session_url = None

        if self._http:
            await self._http.close()
            self._http = None

    async def _poll(self):
        while True:
            params = {"maxev": 1, "rid": int(time.time() * 1000)}
            async with self._http.get(self._session_url, params=params) as response:
                data = await response.json()
                if data["janus"] == "event":
                    plugin = self._plugins.get(data["sender"], None)
                    if plugin:
                        await plugin._queue.put(data)
                    else:
                        print(data)


async def publish(plugin, player):
    """
    Send video to the room.
    """
    turnServer = RTCIceServer(urls="turn:myTurnServer", username="test", credential="123456")
    rtcConfig = RTCConfiguration(iceServers=[turnServer])
    pc = RTCPeerConnection(rtcConfig)

    # configure media
    media = {"audio": True, "video": False}

    # send offer
    print("added audio track")
    sender = pc.addTrack(player.audio)

    print("create offer")
    pcOffer = await pc.createOffer()
    # print(pcOffer)

    print("set local description")
    await pc.setLocalDescription(pcOffer)
    request = {"request": "configure"}
    request.update(media)

    print("send sdp request")
    response = await plugin.send(
        {
            "body": request,
            "jsep": {
                "sdp": pc.localDescription.sdp,
                "trickle": False,
                "type": pc.localDescription.type,
            },
        }
    )

    # apply answer
    print("set remote description")
    await pc.setRemoteDescription(
        RTCSessionDescription(
            sdp=response["jsep"]["sdp"], type=response["jsep"]["type"]
        )
    )

    # @sender.transport.on('statechange')
    # async def change_state():
    #     print('change sender state to %s', sender.transport.state)

    @pc.on("track")
    async def on_track(track):
        print("Track %s received" % track.kind)
        
        # if track.kind == "video":
        #     recorder.addTrack(track)
        # if track.kind == "audio":
        #     recorder.addTrack(track)


async def run(player, room, session):
    print("create session")
    await session.create()

    # join video room
    print("join room")
    plugin = await session.attach("janus.plugin.audiobridge")
    print("check exists")
    # exists = await plugin.post(
    #     {
    #         "body":{
    #             "request": "exists",
    #             "room": room,
    #         }
    #     }
    # )
    # availableRooms = await plugin.post(
    #     {
    #         "body":{
    #             "request": "list",
    #         }
    #     }
    # )
    # print(availableRooms)

    response = await plugin.send(
        {
            "body": {
                "display": "[\"86655584392323072\",\"Noisy\",\"https://xms-dev-1251001060.cos.ap-guangzhou.myqcloud.com/x-project/user-upload-files/d42ca330d93d88e0e7c19e2b2fe42fb5.jpg\"]",
                "request": "join",
                "room": room,
            }
        }
    )

    print("before publish")
    await publish(plugin=plugin, player=player)
    print("after publish")
        

    # exchange media for 1 minute
    print("Exchanging media")
    await asyncio.sleep(600)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Janus")
    parser.add_argument("url", help="Janus root URL, e.g. http://localhost:8088/janus")
    parser.add_argument(
        "--room",
        type=int,
        default=1234,
        help="The video room ID to join (default: 1234).",
    ),
    parser.add_argument("--play-from", help="Read the media from a file and sent it."),
    parser.add_argument("--record-to", help="Write received media to a file."),
    parser.add_argument("--verbose", "-v", action="count")
    args = parser.parse_args()

    if args.verbose:
        logging.basicConfig(level=logging.DEBUG)

    # create signaling and peer connection
    session = JanusSession(args.url)

    # create media source
    if args.play_from:
        player = MediaPlayer(args.play_from)
    else:
        player = None


    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(
            run(player=player, room=str(args.room), session=session)
        )
    except KeyboardInterrupt:
        pass
    finally:
        print("session destroy")
        loop.run_until_complete(session.destroy())

        # close peer connections
        coros = [pc.close() for pc in pcs]
        loop.run_until_complete(asyncio.gather(*coros))

```

Server logs:
![image](https://user-images.githubusercontent.com/22998430/104810663-0c297600-57ab-11eb-8ff4-97c2f34e5c32.png)

Client packets:
![image](https://user-images.githubusercontent.com/22998430/104810675-16e40b00-57ab-11eb-8c26-3cbbed306f7e.png)

**Comment by jlaine** [comment]
Thanks for the detailed information, but this ticket is kind of all over the place!

To reduce the number of unknowns can you try without TURN for a start? Until a very recent release of `aioice` there were some serious issues with TURN.

Secondly in the wireshark capture I see there is some packet fragmentation going on which makes me wonder if one of the endpoints is sending overly large UDP datagrams.

**Comment by jonassmedegaard** [comment]
@zhiweny1122 I believe you should be permitted to close this issue yourself.  Please do that if possible.
