### ISSUE TITLE
Installation fails, with   error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by snroeust** [aiortc/aiortc#474]
Hi, I tried to install aiortc via pip3 for python 3.9 in Raspbian for BananaPi zero M2, but it always fails with the error message: 

> 
    ERROR: Command errored out with exit status 1:
     command: /home/pi/venv/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-e0eq4si7/aiortc_54f1b5ac04ae401da295de2039ff088b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-e0eq4si7/aiortc_54f1b5ac04ae401da295de2039ff088b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tvov8nqm
         cwd: /tmp/pip-install-e0eq4si7/aiortc_54f1b5ac04ae401da295de2039ff088b/
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /home/pi/venv/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-sde7wf5x/cffi_1ce180ab1836408bacaaddff8196a522/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-sde7wf5x/cffi_1ce180ab1836408bacaaddff8196a522/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-v4xbzrd4
           cwd: /tmp/pip-wheel-sde7wf5x/cffi_1ce180ab1836408bacaaddff8196a522/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cffi
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/home/pi/venv/lib/python3.9/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/pi/venv/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpicwgl04_', '--quiet', 'cffi>=1.0.0']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-e0eq4si7/aiortc_54f1b5ac04ae401da295de2039ff088b/setup.py", line 35, in <module>
        setuptools.setup(
      File "/home/pi/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "/home/pi/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/pi/venv/lib/python3.9/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/home/pi/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "/home/pi/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "/home/pi/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1076, in obtain
        return installer(requirement)
      File "/home/pi/venv/lib/python3.9/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/pi/venv/lib/python3.9/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/home/pi/venv/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpicwgl04_', '--quiet', 'cffi>=1.0.0']' returned non-zero exit status 1.
    ----------------------------------------

So I run pip3 install wheel but I still get the same Error Message, can anybody help me ?
The Image I used for the Banana Pi comes from here : http://wiki.banana-pi.org/Banana_Pi_BPI-M2_ZERO#Linux

**Comment by jlaine** [comment]
The error above seems to be while installing `cffi`, not `aiortc` itself, so I'm not sure I can help.
