### ISSUE TITLE
aiortc installation error using pip

### ISSUE THREAD

**Issue by ccschillinger** [aiortc/aiortc#506]
New to aiortc,
Having a similar issue to issue #416, yet that thread did not help me. I am getting the following error when trying to install aiortc using:
`pip install aiortc`

```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jmB27C/aiortc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jmB27C/aiortc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8qiykA
         cwd: /tmp/pip-install-jmB27C/aiortc/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jmB27C/aiortc/setup.py", line 9, in <module>
        with open(about_file, encoding="utf-8") as fp:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Not sure how to rectify/address this issue

**Comment by jlaine** [comment]
The root problem is the same: you are using Python 2, aiortc only supports Python 3.6 and up. Try pip3 install

**Comment by ccschillinger** [comment]
That's exactly it. Thanks
