### ISSUE TITLE
aiortc create Janus meeting room fail

### ISSUE THREAD

**Issue by zhiweny1122** [aiortc/aiortc#522]
I use the aiortc example to connect the janus public website and set the room to 1235
Aiortc failed to create the janus room.
 
python3.6 janus.py https://janus.conf.meetecho.com/janus --play-from 190309153658147087.mp4 --room 1235
Traceback (most recent call last):
  File "janus.py", line 249, in <module>
    run(player=player, recorder=recorder, room=args.room, session=session)
  File "/opt/anoconda3/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "janus.py", line 196, in run
    publishers = response["plugindata"]["data"]["publishers"]
KeyError: 'publishers'

**Comment by zhiweny1122** [comment]
response = await plugin.send(
                {"body": {"request": "create", "description":"test","room": room,"bitrate":4096000,"bitrate_cap":true, "publishers":6, "notify_joining":true }}
        )
I add this statement in subscribe and it failed

**Comment by zhiweny1122** [comment]
resolved
