### ISSUE TITLE
Install aiortc in msys platform

### ISSUE THREAD

**Issue by el07694** [aiortc/aiortc#557]
Hello, is there any plan to have instruction of how we can install aiortc to msys2 (mingw64) platform?

**Comment by jlaine** [comment]
Sure, you've just volunteered to write them!

**Comment by el07694** [comment]
The actual error is:
```

  C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-
w64-mingw32/bin/ld.exe: cannot find -lvpxmt
  collect2.exe: error: ld returned 1 exit status
```

I search the internet for lvpxmt. No results found. I search for vpxmt and i found this links:

[https://voidpoint.io/jonof/eduke32/-/blob/interpolation/platform/Windows/lib/instructions_arm64.txt](https://voidpoint.io/jonof/eduke32/-/blob/interpolation/platform/Windows/lib/instructions_arm64.txt)

I don't know what lvpxmt is (maybe a C++ audio module).

**Comment by el07694** [comment]
Ok, here is the solution.

1. I modified [https://github.com/aiortc/aiortc/blob/main/src/_cffi_src/build_vpx.py](https://github.com/aiortc/aiortc/blob/main/src/_cffi_src/build_vpx.py)

```
'''
if sys.platform == "win32":
    libraries = ["vpxmt"]
else:
    libraries = ["vpx"]
'''
libraries = ["vpx"]
```

2. I run ```pacman -S mingw-w64-x86_64-libvpx```

3. Then git clone, python setup.py build and python setup.py install.

And that's it!

**Comment by el07694** [comment]
A small aiortc app i have made work, but there are some exceptions to handle:

```
Exception in callback _ProactorDatagramTransport._loop_reading(<_OverlappedF...1
.20', 5353))>)
handle: <Handle _ProactorDatagramTransport._loop_reading(<_OverlappedF...1.20',
5353))>)>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:/msys64/mingw64/lib/python3.8/asyncio/proactor_events.py", line 578, i
n _loop_reading
    self._protocol.datagram_received(data, addr)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/aioice/mdns.py", line 55,
in datagram_received
    if isinstance(message, dns.message.QueryMessage):
AttributeError: module 'dns.message' has no attribute 'QueryMessage'
Exception in callback _ProactorDatagramTransport._loop_reading(<_OverlappedF...1
.20', 5353))>)
handle: <Handle _ProactorDatagramTransport._loop_reading(<_OverlappedF...1.20',
5353))>)>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:/msys64/mingw64/lib/python3.8/asyncio/proactor_events.py", line 578, i
n _loop_reading
    self._protocol.datagram_received(data, addr)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/aioice/mdns.py", line 55,
in datagram_received
    if isinstance(message, dns.message.QueryMessage):
AttributeError: module 'dns.message' has no attribute 'QueryMessage'
Exception in callback _ProactorDatagramTransport._loop_reading(<_OverlappedF...1
.20', 5353))>)
handle: <Handle _ProactorDatagramTransport._loop_reading(<_OverlappedF...1.20',
5353))>)>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:/msys64/mingw64/lib/python3.8/asyncio/proactor_events.py", line 578, i
n _loop_reading
    self._protocol.datagram_received(data, addr)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/aioice/mdns.py", line 55,
in datagram_received
    if isinstance(message, dns.message.QueryMessage):
AttributeError: module 'dns.message' has no attribute 'QueryMessage'
Exception in callback _ProactorDatagramTransport._loop_reading(<_OverlappedF...1
.20', 5353))>)
handle: <Handle _ProactorDatagramTransport._loop_reading(<_OverlappedF...1.20',
5353))>)>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:/msys64/mingw64/lib/python3.8/asyncio/proactor_events.py", line 578, i
n _loop_reading
    self._protocol.datagram_received(data, addr)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/aioice/mdns.py", line 55,
in datagram_received
    if isinstance(message, dns.message.QueryMessage):
AttributeError: module 'dns.message' has no attribute 'QueryMessage'
Exception in callback _ProactorDatagramTransport._loop_reading(<_OverlappedF...1
.20', 5353))>)
handle: <Handle _ProactorDatagramTransport._loop_reading(<_OverlappedF...1.20',
5353))>)>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:/msys64/mingw64/lib/python3.8/asyncio/proactor_events.py", line 578, i
n _loop_reading
    self._protocol.datagram_received(data, addr)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/aioice/mdns.py", line 55,
in datagram_received
    if isinstance(message, dns.message.QueryMessage):
AttributeError: module 'dns.message' has no attribute 'QueryMessage'
Exception in callback _ProactorDatagramTransport._loop_reading(<_OverlappedF...1
.20', 5353))>)
handle: <Handle _ProactorDatagramTransport._loop_reading(<_OverlappedF...1.20',
5353))>)>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:/msys64/mingw64/lib/python3.8/asyncio/proactor_events.py", line 578, i
n _loop_reading
    self._protocol.datagram_received(data, addr)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/aioice/mdns.py", line 55,
in datagram_received
    if isinstance(message, dns.message.QueryMessage):
AttributeError: module 'dns.message' has no attribute 'QueryMessage'
Exception in callback _ProactorDatagramTransport._loop_reading(<_OverlappedF...1
.20', 5353))>)
handle: <Handle _ProactorDatagramTransport._loop_reading(<_OverlappedF...1.20',
5353))>)>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:/msys64/mingw64/lib/python3.8/asyncio/proactor_events.py", line 578, i
n _loop_reading
    self._protocol.datagram_received(data, addr)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/aioice/mdns.py", line 55,
in datagram_received
    if isinstance(message, dns.message.QueryMessage):
AttributeError: module 'dns.message' has no attribute 'QueryMessage'
Exception in callback _ProactorDatagramTransport._loop_reading(<_OverlappedF...1
.20', 5353))>)
handle: <Handle _ProactorDatagramTransport._loop_reading(<_OverlappedF...1.20',
5353))>)>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:/msys64/mingw64/lib/python3.8/asyncio/proactor_events.py", line 578, i
n _loop_reading
    self._protocol.datagram_received(data, addr)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/aioice/mdns.py", line 55,
in datagram_received
    if isinstance(message, dns.message.QueryMessage):
AttributeError: module 'dns.message' has no attribute 'QueryMessage'
Exception in callback _ProactorDatagramTransport._loop_reading(<_OverlappedF...1
.20', 5353))>)
handle: <Handle _ProactorDatagramTransport._loop_reading(<_OverlappedF...1.20',
5353))>)>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:/msys64/mingw64/lib/python3.8/asyncio/proactor_events.py", line 578, i
n _loop_reading
    self._protocol.datagram_received(data, addr)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/aioice/mdns.py", line 55,
in datagram_received
    if isinstance(message, dns.message.QueryMessage):
AttributeError: module 'dns.message' has no attribute 'QueryMessage'
Exception in callback _ProactorDatagramTransport._loop_reading(<_OverlappedF...1
.20', 5353))>)
handle: <Handle _ProactorDatagramTransport._loop_reading(<_OverlappedF...1.20',
5353))>)>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:/msys64/mingw64/lib/python3.8/asyncio/proactor_events.py", line 578, i
n _loop_reading
    self._protocol.datagram_received(data, addr)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/aioice/mdns.py", line 55,
in datagram_received
    if isinstance(message, dns.message.QueryMessage):
AttributeError: module 'dns.message' has no attribute 'QueryMessage'
Exception in callback _ProactorDatagramTransport._loop_reading(<_OverlappedF...1
.20', 5353))>)
handle: <Handle _ProactorDatagramTransport._loop_reading(<_OverlappedF...1.20',
5353))>)>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:/msys64/mingw64/lib/python3.8/asyncio/proactor_events.py", line 578, i
n _loop_reading
    self._protocol.datagram_received(data, addr)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/aioice/mdns.py", line 55,
in datagram_received
    if isinstance(message, dns.message.QueryMessage):
AttributeError: module 'dns.message' has no attribute 'QueryMessage'
Exception in callback _ProactorDatagramTransport._loop_reading(<_OverlappedF...1
.20', 5353))>)
handle: <Handle _ProactorDatagramTransport._loop_reading(<_OverlappedF...1.20',
5353))>)>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:/msys64/mingw64/lib/python3.8/asyncio/proactor_events.py", line 578, i
n _loop_reading
    self._protocol.datagram_received(data, addr)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/aioice/mdns.py", line 55,
in datagram_received
    if isinstance(message, dns.message.QueryMessage):
AttributeError: module 'dns.message' has no attribute 'QueryMessage'
```

With native windows 10 python, this exceptions aren't displayed.

**Comment by jlaine** [comment]
The second issue (about dnspython) is unrelated, just updated to dnspython >= 2.0.0.

**Comment by jlaine** [comment]
I'm closing this, there is not more reference to "vpxmt" in our code.
