### ISSUE TITLE
MediaPlayer is invalid

### ISSUE THREAD

**Issue by Canees** [aiortc/aiortc#563]
I have installed AIORTC with PI, and you can get media stream without browser by looking at its documents. Examples are as follows:
self.webcam = MediaPlayer('/pythonAiortc/132.mp4')
self.relay = MediaRelay()
return None, self.relay.subscribe(self.webcam.video)

But execution has been problematic:
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/pythonAiortc/send.py", line 28, in run
audio, video = self.create_local_tracks()
File "/pythonAiortc/send.py", line 22, in create_local_tracks
self.webcam = MediaPlayer('/pythonAiortc/132.mp4')
File "/usr/local/lib/python3.7/dist-packages/aiortc/contrib/media.py", line 252, in init
self.__video = PlayerStreamTrack(self, kind="video")
File "/usr/local/lib/python3.7/dist-packages/aiortc/contrib/media.py", line 166, in init
self._queue = asyncio.Queue()
File "/usr/lib/python3.7/asyncio/queues.py", line 34, in init
self._loop = events.get_event_loop()
File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
% threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.
Also use :
webcam = MediaPlayer("/dev/video0", format="v4l2", options={"framerate": "30", "video_size": "640x480"})
relay = MediaRelay()
But it doesn't seem to be doing anything?

**Comment by lgrahl** [comment]
You need to run it in an event loop. Please, invest some time on your own into researching what an exception means / how Python's asyncio works before opening issues here.
