### ISSUE TITLE
no attribute Query Message  in dns.message

### ISSUE THREAD

**Issue by version0chiro** [aiortc/aiortc#577]
Running a custom code derived from the example server, I end up getting an attribute error with this message:

```
ERROR:asyncio:Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tf-gpu-1.13\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "D:\Anaconda3\envs\tf-gpu-1.13\lib\asyncio\selector_events.py", line 1068, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "D:\Anaconda3\envs\tf-gpu-1.13\lib\site-packages\aioice\mdns.py", line 55, in datagram_received
    if isinstance(message, dns.message.QueryMessage):
AttributeError: module 'dns.message' has no attribute 'QueryMessage'
ERROR:asyncio:Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tf-gpu-1.13\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "D:\Anaconda3\envs\tf-gpu-1.13\lib\asyncio\selector_events.py", line 1068, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "D:\Anaconda3\envs\tf-gpu-1.13\lib\site-packages\aioice\mdns.py", line 55, in datagram_received
    if isinstance(message, dns.message.QueryMessage):
AttributeError: module 'dns.message' has no attribute 'QueryMessage'

```

Can someone help with this issue?

**Comment by jlaine** [comment]
You need a more recent version of dnspython, see:

https://github.com/aiortc/aioice/commit/26abbb23e485aed9a338208f53b81727c3ca6206
