### ISSUE TITLE
non-strictly-monotonic PTS when recording

### ISSUE THREAD

**Issue by glebmxyz** [aiortc/aiortc#580]
Hello! I've been working with aiortc a lot lately. Thank you for your project, @jlaine!

## The Problem
When I try to record video with server example i get the following output:
```
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
INFO:pc:PeerConnection(5638e909-9064-42e6-b498-0b8b7f6ae66e) Created for 127.0.0.1
/home/glebmxyz/work/aiortc/examples/server/venv/lib/python3.9/site-packages/aiortc/rtcdtlstransport.py:211: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  _openssl_assert(lib.SSL_CTX_use_certificate(ctx, self._cert._x509) == 1)  # type: ignore
INFO:pc:PeerConnection(5638e909-9064-42e6-b498-0b8b7f6ae66e) Track video received
/home/glebmxyz/work/aiortc/examples/server/venv/lib/python3.9/site-packages/aiortc/rtcdtlstransport.py:186: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  value=certificate_digest(self._cert._x509),  # type: ignore
INFO:aioice.ice:Connection(0) Check CandidatePair(('192.168.88.254', 38006) -> ('192.168.88.254', 42846)) State.FROZEN -> State.WAITING
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 33384) -> ('192.168.88.254', 42846)) State.FROZEN -> State.WAITING
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.19.0.1', 60979) -> ('192.168.88.254', 42846)) State.FROZEN -> State.WAITING
INFO:pc:PeerConnection(5638e909-9064-42e6-b498-0b8b7f6ae66e) Connection state is connecting
INFO:aioice.ice:Connection(0) Check CandidatePair(('192.168.88.254', 38006) -> ('192.168.88.254', 42846)) State.WAITING -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('192.168.88.254', 38006) -> ('192.168.88.254', 42846)) State.IN_PROGRESS -> State.SUCCEEDED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.17.0.1', 33384) -> ('192.168.88.254', 42846)) State.WAITING -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.19.0.1', 60979) -> ('192.168.88.254', 42846)) State.WAITING -> State.FAILED
INFO:aioice.ice:Connection(0) ICE completed
INFO:pc:PeerConnection(5638e909-9064-42e6-b498-0b8b7f6ae66e) Connection state is connected
[libx264 @ 0x2e0e000] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x2e0e000] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x2e0e000] 264 - core 161 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=7 lookahead_threads=7 sliced_threads=1 slices=7 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=1024 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[libx264 @ 0x2e0e000] non-strictly-monotonic PTS
[libx264 @ 0x2e0e000] non-strictly-monotonic PTS
[libx264 @ 0x2e0e000] non-strictly-monotonic PTS
[libx264 @ 0x2e0e000] non-strictly-monotonic PTS
[libx264 @ 0x2e0e000] non-strictly-monotonic PTS
[libx264 @ 0x2e0e000] non-strictly-monotonic PTS
[libx264 @ 0x2e0e000] non-strictly-monotonic PTS
[libx264 @ 0x2e0e000] non-strictly-monotonic PTS
[libx264 @ 0x2e0e000] non-strictly-monotonic PTS
[libx264 @ 0x2e0e000] non-strictly-monotonic PTS
[libx264 @ 0x2e0e000] non-strictly-monotonic PTS
[libx264 @ 0x2e0e000] non-strictly-monotonic PTS
[libx264 @ 0x2e0e000] non-strictly-monotonic PTS
[mp4 @ 0x2df1800] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 95232 >= 95232
INFO:pc:PeerConnection(5638e909-9064-42e6-b498-0b8b7f6ae66e) Track video ended
[mp4 @ 0x2df1800] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 96768 >= 96768
ERROR:asyncio:Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...', 'rec.mp4')>) at /home/glebmxyz/work/aiortc/examples/server/venv/lib/python3.9/site-packages/pyee/_asyncio.py:57
handle: <Handle AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...', 'rec.mp4')>) at /home/glebmxyz/work/aiortc/examples/server/venv/lib/python3.9/site-packages/pyee/_asyncio.py:57>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/glebmxyz/work/aiortc/examples/server/venv/lib/python3.9/site-packages/pyee/_asyncio.py", line 64, in _callback
    self.emit("error", exc)
  File "/home/glebmxyz/work/aiortc/examples/server/venv/lib/python3.9/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/glebmxyz/work/aiortc/examples/server/venv/lib/python3.9/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/home/glebmxyz/work/aiortc/examples/server/server.py", line 156, in on_ended
    await recorder.stop()
  File "/home/glebmxyz/work/aiortc/examples/server/venv/lib/python3.9/site-packages/aiortc/contrib/media.py", line 380, in stop
    self.__container.mux(packet)
  File "av/container/output.pyx", line 204, in av.container.output.OutputContainer.mux
  File "av/container/output.pyx", line 227, in av.container.output.OutputContainer.mux_one
  File "av/container/core.pyx", line 258, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: 'rec.mp4'
^CINFO:pc:PeerConnection(5638e909-9064-42e6-b498-0b8b7f6ae66e) Connection state is closed
Traceback (most recent call last):
  File "av/container/output.pyx", line 25, in av.container.output.close_output
TypeError: 'NoneType' object is not iterable
Exception ignored in: 'av.container.output.OutputContainer.__dealloc__'
Traceback (most recent call last):
  File "av/container/output.pyx", line 25, in av.container.output.close_output
TypeError: 'NoneType' object is not iterable
[libx264 @ 0x2e0e000] frame I:1     Avg QP:17.74  size:  4955
[libx264 @ 0x2e0e000] frame P:59    Avg QP: 7.55  size: 10364
[libx264 @ 0x2e0e000] frame B:171   Avg QP:14.11  size:  1843
[libx264 @ 0x2e0e000] consecutive B-frames:  0.9%  0.9%  1.3% 97.0%
[libx264 @ 0x2e0e000] mb I  I16..4: 54.5% 42.1%  3.4%
[libx264 @ 0x2e0e000] mb P  I16..4:  3.5%  3.0%  1.3%  P16..4: 44.7%  9.4%  5.5%  0.0%  0.0%    skip:32.6%
[libx264 @ 0x2e0e000] mb B  I16..4:  0.2%  0.1%  0.0%  B16..8: 34.0%  1.6%  0.3%  direct: 9.1%  skip:54.7%  L0:45.7% L1:48.7% BI: 5.6%
[libx264 @ 0x2e0e000] final ratefactor: 13.89
[libx264 @ 0x2e0e000] 8x8 transform intra:38.6% inter:37.7%
[libx264 @ 0x2e0e000] coded y,uvDC,uvAC intra: 38.1% 33.7% 26.3% inter: 8.2% 28.9% 9.4%
[libx264 @ 0x2e0e000] i16 v,h,dc,p: 35% 17% 45%  2%
[libx264 @ 0x2e0e000] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 17% 45%  2%  1%  1%  1%  2%  2%
[libx264 @ 0x2e0e000] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 51% 26% 15%  2%  1%  1%  1%  1%  1%
[libx264 @ 0x2e0e000] i8c dc,h,v,p: 69% 19% 10%  1%
[libx264 @ 0x2e0e000] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x2e0e000] ref P L0: 65.3%  9.9% 16.4%  8.4%
[libx264 @ 0x2e0e000] ref B L0: 93.9%  5.1%  1.0%
[libx264 @ 0x2e0e000] ref B L1: 97.0%  3.0%
[libx264 @ 0x2e0e000] kb/s:971.97
```

**Note**: I get the same error when recording in `.avi` and `MPEG-DASH` formats, haven't tried others.

### 1. Framerate

I get this error consistently when actual framerate is greater than what specified in `MediaRecorder`.

```python
class MediaRecorder:

  ...

  def addTrack(self, track):
          """
          Add a track to be recorded.
  
          :param track: A :class:`aiortc.MediaStreamTrack`.
          """
          if track.kind == "audio":
              if self.__container.format.name in ("wav", "alsa"):
                  codec_name = "pcm_s16le"
              elif self.__container.format.name == "mp3":
                  codec_name = "mp3"
              else:
                  codec_name = "aac"
              stream = self.__container.add_stream(codec_name)
          else:
              if self.__container.format.name == "image2":
                  stream = self.__container.add_stream("png", rate=30)
                  stream.pix_fmt = "rgb24"
              else:
                  stream = self.__container.add_stream("libx264", rate=30)
                  stream.pix_fmt = "yuv420p"
          self.__tracks[track] = MediaRecorderContext(stream)
```
#### Solution
You can monkey-patch the rate parameter on line 358 in `media.py`  to "solve" this problem
Ex.:
```python
stream = self.__container.add_stream("libx264", rate=60)
```
I think you can put whatever value you want because I got away with 300 fps.

This problem was mentioned in #546.

I wrote a script for debugging:

```python
import argparse
import asyncio
import json

import aiohttp
from aiortc import RTCPeerConnection
from aiortc.contrib.media import MediaPlayer
from aiortc.rtcsessiondescription import RTCSessionDescription


async def stream(duration: int,
                 framerate: int,
                 width: int,
                 height: int) -> None:
    pc = RTCPeerConnection()
    video = MediaPlayer('testsrc='
                        f'duration={duration}:'
                        f'size={width}x{height}:'
                        f'rate={framerate}', 'lavfi')
    audio = MediaPlayer('sine='
                        f'duration={duration}:'
                        'frequency=1000:'
                        'sample_rate=48000', 'lavfi')
    pc.addTrack(video.video)
    pc.addTrack(audio.audio)
    await pc.setLocalDescription(await pc.createOffer())
    offer = pc.localDescription

    params = {
        'sdp': offer.sdp,
        'type': offer.type,
        'action': 'stream',
        'stream_id': 'ffmpeg'
    }
    async with aiohttp.ClientSession() as session:
        async with session.post('http://localhost:8080/offer',
                                data=json.dumps(params)) as resp:
            print(resp.status)
            resp_json = await resp.json()
            answer = RTCSessionDescription(resp_json['sdp'], resp_json['type'])
            await pc.setRemoteDescription(answer)
            await asyncio.sleep(duration)
            await pc.close()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Test stream'
    )
    parser.add_argument(
        '--duration',
        '-d',
        type=int,
        default=10,
        help='Stream duration in seconds(default: 10)'
    )
    parser.add_argument(
        '--framerate',
        '-f',
        type=int,
        default=30,
        help='Video framerate (default: 30)'
    )
    parser.add_argument(
        '--width',
        '-vw',
        type=int,
        default=640,
        help='Video width (default: 640)'
    )
    parser.add_argument(
        '--height',
        '-vh',
        type=int,
        default=480,
        help='Video height (default: 480)'
    )

    args = parser.parse_args()
    loop = asyncio.get_event_loop()
    loop.run_until_complete(stream(
        duration=args.duration,
        framerate=args.framerate,
        width=args.width,
        height=args.height
    ))
```

### 2. PTS
[What is PTS?](https://stackoverflow.com/a/58268695)

I tracked PTS of frames in `RemoteStreamTrack` and got:
```
2880
5760
8640
11880
14760
...
```
When it should be more like:
```
0
3000
6000
9000
...
```
**But sometimes it works ok with former PTS.**
#### Solution
I wrap `RemoteStreamTrack` in class that normalizes timestamps:
```python 
from aiortc.mediastreams import VideoStreamTrack
from aiortc.rtcrtpreceiver import RemoteStreamTrack
from av.frame import Frame


class RemoteVideoStreamTrack(VideoStreamTrack):
    '''
    A video track with normalized PTS
    '''
    def __init__(self, track: RemoteStreamTrack) -> None:
        super().__init__()
        self.track = track

    async def recv(self) -> Frame:
        frame = await self.track.recv()
        pts, time_base = await self.next_timestamp()
        print(pts)
        frame.pts = pts
        frame.time_base = time_base
        return frame
```

In `VideoStreamTrack` FPS is hardcoded to 30 but you can monkey-patch it in `media.py`.

**Comment by bmsan** [comment]
@glebmxyz This is also related with #https://github.com/aiortc/aiortc/issues/331

**Comment by jlaine** [comment]
How can I trigger this?

**Comment by jlaine** [comment]
Duplicate of #520
