### ISSUE TITLE
Cannot run apprtc examples

### ISSUE THREAD

**Issue by jimmyd-be** [aiortc/aiortc#622]
When running aiortc example I'm getting following error:
`Traceback (most recent call last):  
  File "/home/test/Downloads/aiortc-main/examples/apprtc/apprtc.py", line 9, in <module>  
    from aiortc import (  
  File "/home/test/Downloads/aiortc-main/src/aiortc/__init__.py", line 23, in <module>  
    from .rtcpeerconnection import RTCPeerConnection  
  File "/home/test/Downloads/aiortc-main/src/aiortc/rtcpeerconnection.py", line 11, in <module>  
    from .codecs import CODECS, HEADER_EXTENSIONS, is_rtx  
  File "/home/test/Downloads/aiortc-main/src/aiortc/codecs/__init__.py", line 15, in <module>  
    from .opus import OpusDecoder, OpusEncoder  
  File "/home/test/Downloads/aiortc-main/src/aiortc/codecs/opus.py", line 9, in <module>  
    from ._opus import ffi, lib  
ModuleNotFoundError: No module named 'aiortc.codecs._opus'`

I tried running it on Kubuntu 21.04 and also in a pyton venv. Do I something wrong by just running the apprtc.py file

**Comment by jlaine** [comment]
You seem to be trying to be using a raw checkout of `aiortc` but did not actually install it.

`pip install -e .`
