### ISSUE TITLE
TCP/UNIX not working with DataChannel/VideoStream Example

### ISSUE THREAD

**Issue by tejas-polakam** [aiortc/aiortc#723]
When I try running the datachannel-cli example on MacOs M1 Monetery(12.3.1), I get the blocking write error.

```
Traceback (most recent call last):
  File "/Users/tejaspolakam/Desktop/testaiortc/aiortc/examples/datachannel-cli/cli.py", line 119, in <module>
    loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/tejaspolakam/Desktop/testaiortc/aiortc/examples/datachannel-cli/cli.py", line 93, in run_offer
    await signaling.send(pc.localDescription)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiortc/contrib/signaling.py", line 71, in send
    self._write_pipe.write(object_to_string(descr) + "\n")
BlockingIOError: [Errno 35] write could not complete without blocking
```

Per the other issues on this topic, I realize that it is a MacOs problem regarding the Copy Paste Socket. However when trying to execute the datachannel-cli example with the TCP/Unix socket the excecution freezes and the offer is not printed to the console.

TCP Example

command `` python3 cli.py offer --signaling tcp-socket --verbose``

```

DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceGatheringState new -> gathering
DEBUG:aioice.ice:Connection(0) protocol(0) connection_made(<_SelectorDatagramTransport fd=6 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(1) connection_made(<_SelectorDatagramTransport fd=7 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(2) connection_made(<_SelectorDatagramTransport fd=8 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(3) connection_made(<_SelectorDatagramTransport fd=9 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(4) connection_made(<_SelectorDatagramTransport fd=10 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(1) > ('142.250.9.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'x6S\x0c\xc2\xbc\xb3\xe0\xc2\xf6\x08\x10')
DEBUG:aioice.ice:Connection(0) protocol(0) > ('142.250.9.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xa5}~\x9at\x81\x80CYJz\x81')
DEBUG:aioice.ice:Connection(0) protocol(1) < ('142.250.9.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'x6S\x0c\xc2\xbc\xb3\xe0\xc2\xf6\x08\x10')
DEBUG:aioice.ice:Connection(0) protocol(0) < ('142.250.9.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\xa5}~\x9at\x81\x80CYJz\x81')
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceGatheringState gathering -> complete

```

Unix Socket

Command: `` python3 cli.py offer --signaling unix-socket --verbose``

```
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceGatheringState new -> gathering
DEBUG:aioice.ice:Connection(0) protocol(0) connection_made(<_SelectorDatagramTransport fd=6 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(1) connection_made(<_SelectorDatagramTransport fd=7 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(2) connection_made(<_SelectorDatagramTransport fd=8 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(3) connection_made(<_SelectorDatagramTransport fd=9 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(4) connection_made(<_SelectorDatagramTransport fd=10 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(0) > ('142.250.9.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'9\xb1\x81\x97\xf7\xc7\xb6\x9b6\xb4_\xda')
DEBUG:aioice.ice:Connection(0) protocol(1) > ('142.250.9.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xd4\x9f:\xc7\xcc8\xab%\x98\x1e\\\x03')
DEBUG:aioice.ice:Connection(0) protocol(1) < ('142.250.9.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\xd4\x9f:\xc7\xcc8\xab%\x98\x1e\\\x03')
DEBUG:aioice.ice:Connection(0) protocol(0) > ('142.250.9.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'9\xb1\x81\x97\xf7\xc7\xb6\x9b6\xb4_\xda')
DEBUG:aioice.ice:Connection(0) protocol(0) < ('142.250.9.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'9\xb1\x81\x97\xf7\xc7\xb6\x9b6\xb4_\xda')
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceGatheringState gathering -> complete

```

The same results when trying the Videostream Example CLI

Is this an issue with Macos or an issue with the examples themselves?

**Comment by jlaine** [comment]
I don't have a Mac so I cannot investigate this myself
