### ISSUE TITLE
videostream-cli doesn't work on windows

### ISSUE THREAD

**Issue by ValerioB88** [aiortc/aiortc#774]
Hi. Thank you for your tool.
Unforunately I can't make the example to run on windows (it works on my Linux machine).
I run `python cli.py offer` and get this printed:
```
Exception in callback _ProactorReadPipeTransport._loop_reading()
handle: <Handle _ProactorReadPipeTransport._loop_reading()>
Traceback (most recent call last):
  File "C:\Users\valer\miniconda3\lib\asyncio\proactor_events.py", line 299, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 32768)
  File "C:\Users\valer\miniconda3\lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
  File "C:\Users\valer\miniconda3\lib\asyncio\windows_events.py", line 723, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 6] The handle is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\valer\miniconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\valer\miniconda3\lib\asyncio\proactor_events.py", line 309, in _loop_reading
    self._fatal_error(exc, 'Fatal read error on pipe transport')
  File "C:\Users\valer\miniconda3\lib\asyncio\proactor_events.py", line 131, in _fatal_error
    self._force_close(exc)
  File "C:\Users\valer\miniconda3\lib\asyncio\proactor_events.py", line 134, in _force_close
    if self._empty_waiter is not None and not self._empty_waiter.done():
AttributeError: '_ProactorReadPipeTransport' object has no attribute '_empty_waiter'
C:\Users\valer\miniconda3\lib\site-packages\aiortc\rtcdtlstransport.py:211: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  _openssl_assert(lib.SSL_CTX_use_certificate(ctx, self._cert._x509) == 1)  # type: ignore
C:\Users\valer\miniconda3\lib\site-packages\aiortc\rtcdtlstransport.py:186: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  value=certificate_digest(self._cert._x509),  # type: ignore
-- Please send this message to the remote party --
{"sdp": "v=0\r\no=- 3872783261 3872783261 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic:WMS *\r\nm=video 61819 UDP/TLS/RTP/SAVPF 97 98 99 100 101 102\r\nc=IN IP4 172.21.178.37\r\na=sendrecv\r\na=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=mid:0\r\na=msid:9c7caa7e-5960-47a9-9871-7af45309decf b4527ca8-9f75-4bb4-b160-eaa8c4f56a16\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-mux\r\na=ssrc-group:FID 1208456129 974422122\r\na=ssrc:1208456129 cname:d9207b2b-b8c9-4f00-9976-572f91dbd6d3\r\na=ssrc:974422122 cname:d9207b2b-b8c9-4f00-9976-572f91dbd6d3\r\na=rtpmap:97 VP8/90000\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 goog-remb\r\na=rtpmap:98 rtx/90000\r\na=fmtp:98 apt=97\r\na=rtpmap:99 H264/90000\r\na=rtcp-fb:99 nack\r\na=rtcp-fb:99 nack pli\r\na=rtcp-fb:99 goog-remb\r\na=fmtp:99 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:100 rtx/90000\r\na=fmtp:100 apt=99\r\na=rtpmap:101 H264/90000\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=rtcp-fb:101 goog-remb\r\na=fmtp:101 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:102 rtx/90000\r\na=fmtp:102 apt=101\r\na=candidate:9257962579a9e165e45035d124bf70f6 1 udp 2130706431 172.21.178.37 61819 typ host\r\na=candidate:fd5d7e4592c49d27c349be1a4fd42f11 1 udp 2130706431 2001:630:e4:4280::1169 61820 typ host\r\na=candidate:82106a16154025a8c79f9bf0de3a3f39 1 udp 2130706431 192.168.1.11 61821 typ host\r\na=candidate:287b29102e73fb7f49e5fbccdf977807 1 udp 1694498815 2.44.141.236 27398 typ srflx raddr 192.168.1.11 rport 61821\r\na=end-of-candidates\r\na=ice-ufrag:tkrG\r\na=ice-pwd:A4vvD9DBxHcD3Ivy55NVF6\r\na=fingerprint:sha-256 4E:0B:83:D3:5B:BE:0F:DF:18:D9:04:07:A7:2B:67:8D:9E:85:9E:59:9D:1F:36:03:D3:8F:00:00:F1:C0:83:14\r\na=setup:actpass\r\n", "type": "offer"}

```
Which seems ok.

Then I run on another terminal `python cli.py answer` but I get this
```
Exception in callback _ProactorReadPipeTransport._loop_reading()
handle: <Handle _ProactorReadPipeTransport._loop_reading()>
Traceback (most recent call last):
  File "C:\Users\valer\miniconda3\lib\asyncio\proactor_events.py", line 299, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 32768)
  File "C:\Users\valer\miniconda3\lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
  File "C:\Users\valer\miniconda3\lib\asyncio\windows_events.py", line 723, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 6] The handle is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\valer\miniconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\valer\miniconda3\lib\asyncio\proactor_events.py", line 309, in _loop_reading
    self._fatal_error(exc, 'Fatal read error on pipe transport')
  File "C:\Users\valer\miniconda3\lib\asyncio\proactor_events.py", line 131, in _fatal_error
    self._force_close(exc)
  File "C:\Users\valer\miniconda3\lib\asyncio\proactor_events.py", line 134, in _force_close
    if self._empty_waiter is not None and not self._empty_waiter.done():
AttributeError: '_ProactorReadPipeTransport' object has no attribute '_empty_waiter'
```
I am on Windows 10, this is ran on Python 3.9.12. Let me know if I need to provide any other info.

**Comment by Nielsencu** [comment]
Same here.

It seems like the issue is due to Windows' Proactor Event loop not supporting stdin/stdout files (https://github.com/python/cpython/issues/71019). The mentioned issue is still open, so it seems like its not resolved yet. 

One possible workaround is mentioned in https://stackoverflow.com/questions/31510190/aysncio-cannot-read-stdin-on-windows/36785819#36785819. 

Similar issues :
https://github.com/julianjurai/BOIX-Chat/issues/1

Temporary resolution is https://github.com/aiortc/aiortc/issues/396.

**Comment by jlaine** [comment]
I can confirm this is a duplicate of #396.
