### ISSUE TITLE
unknown bio failure when use datachannel to transmit long msg in version 1.4.0

### ISSUE THREAD

**Issue by dfybc** [aiortc/aiortc#827]
i use aiortc(V1.4.0) to transmit long msg( servel kB ) for some seconds,  the following error occured。
but on aiortc V1.3.2, no such error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiortc/rtcsctptransport.py", line 1676, in _data_channel_flush
    ordered=channel.ordered,
  File "/usr/local/lib/python3.7/dist-packages/aiortc/rtcsctptransport.py", line 1327, in _send
    await self._transmit()
  File "/usr/local/lib/python3.7/dist-packages/aiortc/rtcsctptransport.py", line 1550, in _transmit
    await self._send_chunk(chunk)
  File "/usr/local/lib/python3.7/dist-packages/aiortc/rtcsctptransport.py", line 1339, in _send_chunk
    chunk,
  File "/usr/local/lib/python3.7/dist-packages/aiortc/rtcdtlstransport.py", line 592, in _send_data
    await self._write_ssl()
  File "/usr/local/lib/python3.7/dist-packages/aiortc/rtcdtlstransport.py", line 630, in _write_ssl
    data = self.ssl.bio_read(1500)
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/SSL.py", line 2029, in bio_read
    self._handle_bio_errors(self._from_ssl, result)
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/SSL.py", line 2004, in _handle_bio_errors
    raise ValueError("unknown bio failure")
ValueError: unknown bio failure

**Comment by jlaine** [comment]
Please include a minimal reproduction.
