### ISSUE TITLE
how to add multiple local mp4 video in the webcam.py ?

### ISSUE THREAD

**Issue by MonicaCullen** [aiortc/aiortc#854]
hi,

I got an error when I tried to open multiple local mp4 to add to the RTCPeerConnection object, Here is the code:
```
import argparse
import asyncio
import json
import logging
import os
import platform
import ssl

from moviepy.editor import *
from aiohttp import web
from aiortc import RTCPeerConnection, RTCSessionDescription
from aiortc.contrib.media import MediaPlayer, MediaRelay
from aiortc.rtcrtpsender import RTCRtpSender

ROOT = os.path.dirname(__file__)


relay = None
webcam = None

def create_local_tracks(play_from, decode):
    global relay, webcam

    if play_from:
        player = MediaPlayer(play_from, decode=decode)
        return player.audio, player.video
    else:
        options = {"framerate": "30", "video_size": "640x480"}
        if relay is None:
            if platform.system() == "Darwin":
                webcam = MediaPlayer(
                    "default:none", format="avfoundation", options=options
                )
            elif platform.system() == "Windows":
                webcam = MediaPlayer(
                    "video=Integrated Camera", format="dshow", options=options
                )
            else:
                webcam = MediaPlayer("/dev/video0", format="v4l2", options=options)
            relay = MediaRelay()
        return None, relay.subscribe(webcam.video)


def force_codec(pc, sender, forced_codec):
    kind = forced_codec.split("/")[0]
    codecs = RTCRtpSender.getCapabilities(kind).codecs
    transceiver = next(t for t in pc.getTransceivers() if t.sender == sender)
    transceiver.setCodecPreferences(
        [codec for codec in codecs if codec.mimeType == forced_codec]
    )


async def index(request):
    content = open(os.path.join(ROOT, "index.html"), "r").read()
    return web.Response(content_type="text/html", text=content)


async def javascript(request):
    content = open(os.path.join(ROOT, "client.js"), "r").read()
    return web.Response(content_type="application/javascript", text=content)


async def offer(request):
    params = await request.json()

    offer = RTCSessionDescription(sdp=params["sdp"], type=params["type"])

    pc = RTCPeerConnection()
    pcs.add(pc)

    @pc.on("connectionstatechange")
    async def on_connectionstatechange():
        print("Connection state is %s" % pc.connectionState)
        if pc.connectionState == "failed":
            await pc.close()
            pcs.discard(pc)

    # # open media source
    # audio, video = create_local_tracks(
    #     args.play_from, decode=not args.play_without_decoding
    # )
    # --------------------add multiple video ---------------------------------
    path = ["D:/test.mp4", "D:/test1.mp4"]
    for play_from in path:
        audio, video = create_local_tracks(
            play_from, decode=not args.play_without_decoding
        )
        if audio:
            pc.addTrack(audio)

        if video:
            pc.addTrack(video)
    # -----------------------add multiple video ------------------------------

    # if audio:
    #     audio_sender = pc.addTrack(audio)
    if args.audio_codec:
        force_codec(pc, audio_sender, args.audio_codec)
    elif args.play_without_decoding:
        raise Exception("You must specify the audio codec using --audio-codec")

    # if video:
    #     video_sender = pc.addTrack(video)
    if args.video_codec:
        force_codec(pc, video_sender, args.video_codec)
    elif args.play_without_decoding:
        raise Exception("You must specify the video codec using --video-codec")

    await pc.setRemoteDescription(offer)

    answer = await pc.createAnswer()
    await pc.setLocalDescription(answer)

    return web.Response(
        content_type="application/json",
        text=json.dumps(
            {"sdp": pc.localDescription.sdp, "type": pc.localDescription.type}
        ),
    )


pcs = set()


async def on_shutdown(app):
    # close peer connections
    coros = [pc.close() for pc in pcs]
    await asyncio.gather(*coros)
    pcs.clear()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="WebRTC webcam demo")
    parser.add_argument("--cert-file", help="SSL certificate file (for HTTPS)")
    parser.add_argument("--key-file", help="SSL key file (for HTTPS)")
    parser.add_argument("--play-from", help="Read the media from a file and sent it."),
    parser.add_argument(
        "--play-without-decoding",
        help=(
            "Read the media without decoding it (experimental). "
            "For now it only works with an MPEGTS container with only H.264 video."
        ),
        action="store_true",
    )
    parser.add_argument(
        "--host", default="0.0.0.0", help="Host for HTTP server (default: 0.0.0.0)"
    )
    parser.add_argument(
        "--port", type=int, default=8080, help="Port for HTTP server (default: 8080)"
    )
    parser.add_argument("--verbose", "-v", action="count")
    parser.add_argument(
        "--audio-codec", help="Force a specific audio codec (e.g. audio/opus)"
    )
    parser.add_argument(
        "--video-codec", help="Force a specific video codec (e.g. video/H264)"
    )

    args = parser.parse_args()

    if args.verbose:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    if args.cert_file:
        ssl_context = ssl.SSLContext()
        ssl_context.load_cert_chain(args.cert_file, args.key_file)
    else:
        ssl_context = None

    app = web.Application()
    app.on_shutdown.append(on_shutdown)
    app.router.add_get("/", index)
    app.router.add_get("/client.js", javascript)
    app.router.add_post("/offer", offer)
    web.run_app(app, host=args.host, port=args.port, ssl_context=ssl_context)
```

**below is the error:**
```
INFO:aiohttp.access:127.0.0.1 [04/Apr/2023:09:04:25 +0000] "GET / HTTP/1.1" 200 979 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
INFO:aiohttp.access:127.0.0.1 [04/Apr/2023:09:04:25 +0000] "GET /client.js HTTP/1.1" 200 2478 "http://127.0.0.1:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
INFO:aioice.ice:Connection(3) Remote candidate "ea686aef-2a55-4084-bebe-0c0ae1b4597b.local" resolved to 10.102.133.122
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "C:\Users\wuling\anaconda3\lib\site-packages\aiohttp\web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "C:\Users\wuling\anaconda3\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "D:\PycharmProjects\aiortc\examples\webcam\webcam.py", line 150, in offer
  File "C:\Users\wuling\anaconda3\lib\site-packages\aiortc\rtcpeerconnection.py", line 786, in setLocalDescription
    t._currentDirection = and_direction(t.direction, t._offerDirection)
  File "C:\Users\wuling\anaconda3\lib\site-packages\aiortc\rtcpeerconnection.py", line 259, in and_direction
    return sdp.DIRECTIONS[sdp.DIRECTIONS.index(a) & sdp.DIRECTIONS.index(b)]
ValueError: None is not in list
INFO:aiohttp.access:127.0.0.1 [04/Apr/2023:09:04:27 +0000] "POST /offer HTTP/1.1" 500 244 "http://127.0.0.1:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
```
Is there any idea to solve this problem?

thanks for a lot!

**Comment by mariokrous** [comment]
I'm a bit confused. 
First of all, I cannot reproduce the error and it seems that the error you are getting has nothing to do with adding multiple local  mp4 video.

Also, you are using function " create local tracks" which returns None, relay.subscribe(webcam.video).
So, you are not going to get any local files but your webcam!
You have to use the Media player.

**Comment by MonicaCullen** [comment]
> First of all, I cannot reproduce the error and it seems that the error you are getting has nothing to do with adding multiple local mp4 video.
> 
> Also, you are using function " create local tracks" which returns None, relay.subscribe(webcam.video). So, you are not going to get any local files but your webcam! You have to use the Media player.

Thanks for your reply.
In my code, I have specified the "play_from" to a local mp4 path Although  I didn't use the play_from parameter. So , in the function of create_local_tracks, it would be generate a MediaSreamTrack Object by the MediaPlayer with the input local mp4 path rather than using  the webcam. 

By the way, when I specified the path equal ["D:/test.mp4"] that only have one video, It works fine . But got an error  if  two video given (path = ["D:/test.mp4","D:/test1.mp4] ).
