### ISSUE TITLE
ICE connection is stuck on checking and PeerConnection ConnectionState is stuck on connecting

### ISSUE THREAD

**Issue by pavan7parekh** [aiortc/aiortc#855]
I am currently working on a video calling application for Linux desktops. To establish peer-to-peer connections, I have used aiortc for RTC connections and utilized WebSockets for handling offer, answer, candidate, and message data transactions. Moreover, I have integrated OpenCV for video capture and streaming through aiortc. 

Please have a look at my full code and Logs - Exception and help me for the issue:

```
import asyncio
import json
import websocket
import threading
from aiortc import (RTCIceCandidate,
                    RTCPeerConnection,
                    RTCSessionDescription,
                    VideoStreamTrack,
                    RTCConfiguration,
                    RTCIceServer)

from OpenCVVideoStreamTrack import OpenCVVideoStreamTrack
from VideoReceiver import VideoReceiver

class WebRTCClient:
    def __init__(self, signaling_url, main):
        self.local_video_track = None
        self.Main = main
        self.signaling_url = signaling_url
        self.ws = None

        self.pc = RTCPeerConnection(
            configuration=RTCConfiguration(
                iceServers=[RTCIceServer(urls=["stun:stun1.l.google.com:19302"])]
            )
        )

        self.dc = self.pc.createDataChannel(label="Pavan2Krisha", id=2)
        self.playing = False
        self.pc.on('datachannel', self.on_datachannel)
        self.pc.on('track', self.on_track)

        self.pc.on('iceconnectionstatechange', self.on_iceconnectionstatechange)
        self.pc.on("icecandidate", self.on_icecandidate)
        self.pc.on("icegatheringstatechange", self.on_icegatheringstatechange)
        self.pc.on("connectionstatechange", self.on_connectionstatechange)

        print(f'PC CONNECTION: {self.pc.connectionState}')

        self.connected = asyncio.Event()

    def connect(self):
        self.ws = websocket.WebSocketApp(
            self.signaling_url,
            on_open=self.ws_on_open,
            on_message=self.ws_on_message,
            on_error=self.ws_on_error,
            on_close=self.ws_on_close)
        ws_thread = threading.Thread(target=self.ws.run_forever)
        ws_thread.daemon = True
        ws_thread.start()

    async def create_offer(self):
        try:
            # Add an audio transceiver with sendrecv direction
            self.pc.addTransceiver("audio", direction="sendrecv")
            self.pc.addTransceiver("video", direction="sendrecv")

            if self.local_video_track is None:
                # Capture local video stream
                self.local_video_track = OpenCVVideoStreamTrack()
                # Create a local video receiver thread
                local_video_receiver = VideoReceiver(self.local_video_track)
                local_video_receiver.update_signal.connect(lambda img: self.Main.update_image(img, "local"))
                local_video_receiver.start()

                # Add the local video track to the connection
                self.pc.addTrack(self.local_video_track)

            offer = await self.pc.createOffer()
            await self.pc.setLocalDescription(offer)

            jsoffer = json.dumps(self.pc.localDescription, default=lambda o: o.__dict__, sort_keys=True, indent=4)
            self.ws.send(jsoffer)
            print(f'Offer sent: {jsoffer}')

            await self.connected.wait()

        except Exception as e:
            print(f'Create Offer Exception: {e}')

    async def on_track(self, track):
        print(f"Track {track.kind} received")

        if track.kind == "audio":
            print(f"Track {track.kind} received")
            # self.pc.addTrack(self.player.audio)
            # self.recorder.addTrack(track)
        elif track.kind == "video":
            print(f"Track {track.kind} received")
            while True:
                _, frame = await track.recv()

                if not frame:
                    print(f"Track {track.kind} not received done")
                    break

                # Convert frame to numpy array and update QLabel
                img = frame.to_ndarray(format="bgr24")
                self.Main.update_image(img, "remote")
                print(f"Track {track.kind} received done 2")
            print(f"Track {track.kind} received done")

    def on_datachannel(channel):
        @channel.on("message")
        def on_message(message):
            print(f"datachannel message: {message}")
            if isinstance(message, str) and message.startswith("ping"):
                channel.send("pong" + message[4:])

    def on_iceconnectionstatechange(self):
        print(f"ICE connection state is {self.pc.iceConnectionState}")
        # if self.pc.iceConnectionState == "failed":
        #     await self.pc.close()

    def on_icecandidate(self, candidate):
        if candidate:
            print("Local ICE candidate:", candidate)
            # Send the candidate to the remote peer using your signaling server
            jsoncandidate = json.dumps(candidate, default=lambda o: o.__dict__, sort_keys=True, indent=4)
            print(f"Local ICE candidate: {candidate}")
            self.ws.send(jsoncandidate)

    def on_icegatheringstatechange(self):
        print("ICE gathering state changed to:", self.pc.iceGatheringState)

    def on_connectionstatechange(self):
        print("Connection state %s" % self.pc.connectionState)
        if self.pc.connectionState == "connected":
            self.connected.set()

    async def add_ice_candidate(self, message):
        # message = json.loads(candidate)
        if message["candidate"]["sdp"] is not None:
            parts = message["candidate"]["sdp"].split()
            foundation = parts[0].split(':')[1]
            component_id = int(parts[1])
            protocol = parts[2]
            priority = int(parts[3])
            ip_address = parts[4]
            port = int(parts[5])
            candidate_type = parts[7]

            candidate = RTCIceCandidate(
                foundation=foundation,
                component=component_id,
                protocol=protocol,
                priority=priority,
                ip=ip_address,
                port=port,
                type=candidate_type
            )

            candidate.sdpMLineIndex = message["candidate"]["sdpMLineIndex"]
            candidate.sdpMid = message["candidate"]["sdpMid"]
            await self.pc.addIceCandidate(candidate)

    async def close(self):
        await self.ws.close()
        await self.pc.close()

    def ws_disconnect(self):
        self.ws.close()

    def ws_on_open(self, ws):
        print("WebSocket connection opened")

    def ws_on_message(self, ws, message):
        try:
            msg = self.parse_json(message)
            asyncio.run_coroutine_threadsafe(self.read_message(msg), self.Main.thread_loop)
        except TimeoutError:
            print('The coroutine took too long, cancelling the task...')
        except Exception as exc:
            print(f'The coroutine raised an exception: {exc!r}')

    def ws_on_error(self, ws, error):
        print(f"WebSocket error: {error}")

    def ws_on_close(self, ws):
        print("WebSocket connection closed")

    async def read_message(self, message):
        if message["type"] and message["type"].lower() == "offer":
            try:
                print(f'Received Offer: {message}')
                offer = RTCSessionDescription(message["sdp"], "offer")
                await self.handle_offer(offer)
            except Exception as e:
                print(f'Handle Offer Exception: {e}')

        elif message["type"] and message["type"].lower() == "answer":
            try:
                print(f'Received Answer: {message}')
                # self.pc.addTransceiver("video", direction="sendrecv")
                # self.pc.addTransceiver("audio", direction="sendrecv")

                # Make sure to convert the remote_answer string to a RTCSessionDescription object
                answer = RTCSessionDescription(message["sdp"], message["type"].lower())
                await self.pc.setRemoteDescription(answer)
            except Exception as e:
                print(f'Handle Answer Exception: {e!r}')
            finally:
                print(f'Handle Answer Finally')

        elif message["candidate"]:
            try:
                await asyncio.sleep(1)
                print(f'Received Candidate: {message}')
                await self.add_ice_candidate(message)
            except Exception as e:
                print(f'Handle Candidate Exception: {e}')

    def parse_json(self, json_str):
        # Parse the JSON string into a dictionary
        data = json.loads(json_str)

        # Convert all property names to lowercase
        data = {key.lower(): value for key, value in data.items()}

        return data

    async def handle_offer(self, offer):
        # handle offer

        # Add transceiver
        self.pc.addTransceiver("video")
        self.pc.addTransceiver("audio")

        await asyncio.sleep(0.1)

        await self.pc.setRemoteDescription(offer)

        while self.pc.remoteDescription is None:
            await asyncio.sleep(0.1)

        # send answer
        answer = await self.pc.createAnswer()

        while answer is None:
            await asyncio.sleep(0.1)

        await self.pc.setLocalDescription(answer)

        while self.pc.localDescription is None:
            await asyncio.sleep(0.1)

        # Send the answer to the other peer
        ans = json.dumps(answer, default=lambda o: o.__dict__, sort_keys=True, indent=4)
        self.ws.send(ans)
        print(f"Answer sent {answer}")

```
`

Please have a look at on following logs:

```

PC CONNECTION: new
WebSocket connection opened
called keyboard
ICE gathering state changed to: gathering
ICE gathering state changed to: complete
Offer sent: {
    "sdp": "v=0\r\no=- 3890295292 3890295292 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1 2\r\na=msid-semantic:WMS *\r\nm=audio 57657 UDP/TLS/RTP/SAVPF 96 0 8\r\nc=IN IP4 192.168.0.110\r\na=sendrecv\r\na=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:2 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=mid:0\r\na=msid:76fd2f7f-0fd3-4de9-a2c0-a35da0fd48d4 84c7d7bd-5a4c-4b9a-a2f3-f7aaaef5ece6\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-mux\r\na=ssrc:3912515210 cname:c2e13c60-517f-416f-abe8-99b16b7c92f4\r\na=rtpmap:96 opus/48000/2\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=candidate:bad16f72bdbb2f862ebd231987037880 1 udp 2130706431 192.168.0.110 57657 typ host\r\na=candidate:6ce319e5de49beab3792c85c0b17f1fd 1 udp 1694498815 123.201.0.162 13177 typ srflx raddr 192.168.0.110 rport 57657\r\na=end-of-candidates\r\na=ice-ufrag:BZlo\r\na=ice-pwd:36YEODfxvOBSRaXlaeluNK\r\na=fingerprint:sha-256 25:C0:63:A4:5A:E2:15:59:A5:9C:A3:8F:9E:84:B0:3A:0B:8A:07:B8:9A:98:5D:3B:09:BB:91:E4:1C:F1:7A:40\r\na=setup:actpass\r\nm=video 35315 UDP/TLS/RTP/SAVPF 97 98 99 100 101 102\r\nc=IN IP4 192.168.0.110\r\na=sendrecv\r\na=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=mid:1\r\na=msid:76fd2f7f-0fd3-4de9-a2c0-a35da0fd48d4 8163778f-ebb9-4db1-a47a-e3c51a8fd9ab\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-mux\r\na=ssrc-group:FID 2601178575 2468147998\r\na=ssrc:2601178575 cname:c2e13c60-517f-416f-abe8-99b16b7c92f4\r\na=ssrc:2468147998 cname:c2e13c60-517f-416f-abe8-99b16b7c92f4\r\na=rtpmap:97 VP8/90000\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 goog-remb\r\na=rtpmap:98 rtx/90000\r\na=fmtp:98 apt=97\r\na=rtpmap:99 H264/90000\r\na=rtcp-fb:99 nack\r\na=rtcp-fb:99 nack pli\r\na=rtcp-fb:99 goog-remb\r\na=fmtp:99 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:100 rtx/90000\r\na=fmtp:100 apt=99\r\na=rtpmap:101 H264/90000\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=rtcp-fb:101 goog-remb\r\na=fmtp:101 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:102 rtx/90000\r\na=fmtp:102 apt=101\r\na=candidate:bad16f72bdbb2f862ebd231987037880 1 udp 2130706431 192.168.0.110 35315 typ host\r\na=candidate:6ce319e5de49beab3792c85c0b17f1fd 1 udp 1694498815 123.201.0.162 13175 typ srflx raddr 192.168.0.110 rport 35315\r\na=end-of-candidates\r\na=ice-ufrag:SBzU\r\na=ice-pwd:S66f29xnQcFmAY6WQgsSq7\r\na=fingerprint:sha-256 25:C0:63:A4:5A:E2:15:59:A5:9C:A3:8F:9E:84:B0:3A:0B:8A:07:B8:9A:98:5D:3B:09:BB:91:E4:1C:F1:7A:40\r\na=setup:actpass\r\nm=application 38599 DTLS/SCTP 5000\r\nc=IN IP4 192.168.0.110\r\na=mid:2\r\na=sctpmap:5000 webrtc-datachannel 65535\r\na=max-message-size:65536\r\na=candidate:bad16f72bdbb2f862ebd231987037880 1 udp 2130706431 192.168.0.110 38599 typ host\r\na=candidate:6ce319e5de49beab3792c85c0b17f1fd 1 udp 1694498815 123.201.0.162 13176 typ srflx raddr 192.168.0.110 rport 38599\r\na=end-of-candidates\r\na=ice-ufrag:eltT\r\na=ice-pwd:I0eQkRwPjhJex9fyW2aY9c\r\na=fingerprint:sha-256 25:C0:63:A4:5A:E2:15:59:A5:9C:A3:8F:9E:84:B0:3A:0B:8A:07:B8:9A:98:5D:3B:09:BB:91:E4:1C:F1:7A:40\r\na=setup:actpass\r\n",
    "type": "offer"
}
Received Answer: {'type': 'answer', 'sdp': 'v=0\r\no=- 8581737802341190996 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1 2\r\na=msid-semantic: WMS stream0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 96 0 8\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:OTO8\r\na=ice-pwd:yVl08wDZaMB620qAbDDDIrHu\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 3C:87:C1:4E:12:15:47:73:DD:AE:B6:D5:9F:8B:66:29:69:82:23:4B:2F:1A:42:14:E8:87:02:1F:DD:18:FB:30\r\na=setup:active\r\na=mid:0\r\na=extmap:2 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:96 opus/48000/2\r\na=fmtp:96 minptime=10;useinbandfec=1\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=ssrc:1833517008 cname:DgG4GW/noiE25vBT\r\na=ssrc:1833517008 msid:stream0 audio0\r\na=ssrc:1833517008 mslabel:stream0\r\na=ssrc:1833517008 label:audio0\r\nm=video 9 UDP/TLS/RTP/SAVPF 97 98 101 102\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:OTO8\r\na=ice-pwd:yVl08wDZaMB620qAbDDDIrHu\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 3C:87:C1:4E:12:15:47:73:DD:AE:B6:D5:9F:8B:66:29:69:82:23:4B:2F:1A:42:14:E8:87:02:1F:DD:18:FB:30\r\na=setup:active\r\na=mid:1\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:97 VP8/90000\r\na=rtcp-fb:97 goog-remb\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtpmap:98 rtx/90000\r\na=fmtp:98 apt=97\r\na=rtpmap:101 H264/90000\r\na=rtcp-fb:101 goog-remb\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=fmtp:101 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e034\r\na=rtpmap:102 rtx/90000\r\na=fmtp:102 apt=101\r\na=ssrc-group:FID 2858138652 3273019175\r\na=ssrc:2858138652 cname:DgG4GW/noiE25vBT\r\na=ssrc:2858138652 msid:stream0 video0\r\na=ssrc:2858138652 mslabel:stream0\r\na=ssrc:2858138652 label:video0\r\na=ssrc:3273019175 cname:DgG4GW/noiE25vBT\r\na=ssrc:3273019175 msid:stream0 video0\r\na=ssrc:3273019175 mslabel:stream0\r\na=ssrc:3273019175 label:video0\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\nb=AS:30\r\na=ice-ufrag:OTO8\r\na=ice-pwd:yVl08wDZaMB620qAbDDDIrHu\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 3C:87:C1:4E:12:15:47:73:DD:AE:B6:D5:9F:8B:66:29:69:82:23:4B:2F:1A:42:14:E8:87:02:1F:DD:18:FB:30\r\na=setup:active\r\na=mid:2\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n', 'candidate': None}
Handle Answer Finally
Track audio received
Track audio received
Track video received
Track video received
ICE connection state is checking
Connection state connecting
ICE connection state is completed
**Connection state connected**

Traceback (most recent call last):
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
Task exception was never retrieved
future: <Task finished name='Task-32' coro=<RTCSctpTransport._send_chunk() done, defined at /home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py:1329> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
Task exception was never retrieved
future: <Task finished name='Task-33' coro=<RTCSctpTransport._send_chunk() done, defined at /home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py:1329> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
Task exception was never retrieved
future: <Task finished name='Task-34' coro=<RTCSctpTransport._send_chunk() done, defined at /home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py:1329> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
Task exception was never retrieved
future: <Task finished name='Task-35' coro=<RTCSctpTransport._send_chunk() done, defined at /home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py:1329> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
Task exception was never retrieved
future: <Task finished name='Task-36' coro=<RTCSctpTransport._send_chunk() done, defined at /home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py:1329> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
Task exception was never retrieved
future: <Task finished name='Task-37' coro=<RTCSctpTransport._send_chunk() done, defined at /home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py:1329> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
Task exception was never retrieved
future: <Task finished name='Task-38' coro=<RTCSctpTransport._send_chunk() done, defined at /home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py:1329> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kvl/Documents/GitHub/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected**
```

**Comment by mariokrous** [comment]
This is not an aiortc issue. 
Maybe you should open a new discussion and provide more info about your implementation.

**Comment by pavan7parekh** [comment]
Today' i got new exception in log:

```

ICE connection state is new
Connection state is connecting

Task exception was never retrieved
future: <Task finished name='Task-39' coro=<RTCSctpTransport._transmit() done, defined at /home/kaival/.local/lib/python3.10/site-packages/aiortc/rtcsctptransport.py:1500> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/home/kaival/.local/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1534, in _transmit
    await self._send_chunk(chunk)
  File "/home/kaival/.local/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kaival/.local/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
```

**Comment by pavan7parekh** [comment]
@YuioiuY 

as per my understanding, SDP is main part, You are see candidate in logs is restructured object for web socket message.

**Comment by pavan7parekh** [comment]
> This is not an aiortc issue.
> Maybe you should open a new discussion and provide more info about your implementation.

Could you kindly assist me in identifying the problem? I have already provided comprehensive information, including the source code, logs, and exceptions.

**Comment by YuioiuY** [comment]
@pavan7parekh 

perhaps something like this can help

`await pc.setRemoteDescription(remote_description)
    
    while pc.remoteDescription is None:
        await asyncio.sleep(0.1)

    local_answer = await pc.createAnswer()
    
    while local_answer is None:
        await asyncio.sleep(0.1)

    await pc.setLocalDescription(local_answer)
    
    while pc.localDescription is None:
        await asyncio.sleep(0.1)`
        
I had a similar problem and I was able to solve it with the help of such cycles.

**Comment by pavan7parekh** [comment]
> @pavan7parekh
> 
> perhaps something like this can help
> 
> ` await pc.setRemoteDescription(remote_description)
> 
> ```
> while pc.remoteDescription is None:
>     await asyncio.sleep(0.1)
> 
> local_answer = await pc.createAnswer()
> 
> while local_answer is None:
>     await asyncio.sleep(0.1)
> 
> await pc.setLocalDescription(local_answer)
> 
> while pc.localDescription is None:
>     await asyncio.sleep(0.1)
> ```
> 
> `
> 
> I had a similar problem and I was able to solve it with the help of such cycles.

Not helping it.
Actually, getting exception when handling answer.

**Comment by pavan7parekh** [comment]
Hi @mariokrous  and @jlaine 

I debug the code and found exception "Event loop is closed" on following line of rtcpeerconnection.py file.

Line No 965 :  await dtlsTransport.transport.stop()
Line No 967 :  self.__iceTransports.discard(dtlsTransport.transport)

If i remove those two line then I am not getting exception of "Event loop is closed" on setRemoteDescription(answer) method. but connection is not establish between devices.

Please help me for it.

**Comment by mariokrous** [comment]
Hello,

As I told you before, this is not an aiortc related issue.
I would suggest that you check how asyncio and event loops work and continue debugging your implementation.

**Comment by pavan7parekh** [comment]
Hi @mariokrous 

I updated my code with event loops. you can see.

Now, I am exception from AIORTC py files.
Peer connection is established and suddenly got exception:


```
Traceback (most recent call last):
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
Task exception was never retrieved
future: <Task finished name='Task-32' coro=<RTCSctpTransport._send_chunk() done, defined at /home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py:1329> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
Task exception was never retrieved
future: <Task finished name='Task-33' coro=<RTCSctpTransport._send_chunk() done, defined at /home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py:1329> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
Task exception was never retrieved
future: <Task finished name='Task-34' coro=<RTCSctpTransport._send_chunk() done, defined at /home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py:1329> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
Task exception was never retrieved
future: <Task finished name='Task-35' coro=<RTCSctpTransport._send_chunk() done, defined at /home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py:1329> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
Task exception was never retrieved
future: <Task finished name='Task-36' coro=<RTCSctpTransport._send_chunk() done, defined at /home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py:1329> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
Task exception was never retrieved
future: <Task finished name='Task-37' coro=<RTCSctpTransport._send_chunk() done, defined at /home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py:1329> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
Task exception was never retrieved
future: <Task finished name='Task-38' coro=<RTCSctpTransport._send_chunk() done, defined at /home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py:1329> exception=ConnectionError('Cannot send encrypted data, not connected')>
Traceback (most recent call last):
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcsctptransport.py", line 1334, in _send_chunk
    await self.__transport._send_data(
  File "/home/kaival/Documents/GitHub/Linux-Video-doorbell/_venv/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py", line 576, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected
```

**Comment by zexiplus** [comment]
I saw you use 'self.pc.on("icecandidate", self.on_icecandidate)' in the code, aiortc doesn't support icecandidate event like javascript, so the 'on_icecandidate' will never run

**Comment by pavan7parekh** [comment]
Thanks @mariokrous 
I resolved this issue by manage thread.

**Comment by HysUnknown** [comment]
Hello, I also met the same problem as you, may I ask how you dealt with it? I hope you can solve this problem, thank you!
pc.iceConnectionState is checking
pc.connectionState is connecting
The "connectionState "is always "connecting" and is no longer executed.
