### ISSUE TITLE
Cannot create MediaPlayer instance in seperate thread and event loop to keep persistant.

### ISSUE THREAD

**Issue by R0NAM1** [aiortc/aiortc#950]
- My idea is that on __init__ I create a MediaPlayerPersistanceThread class to handle my Player objects and when they are created, and then I have a run def that does run_forever to the loop, that runs under another thread:

```
class MediaPlayerPersistanceThread:
    def __init__(self):
        self.playerCamDictionary = {}
        self.uuidRelays = {}
        self.relay = MediaRelay()

        # Run an event loop in this thread
        self.loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self.loop)


        

    def returnTrack(self, dockerIp, audioOrVideo, uuid):
        # Check if current cam is in relayCamDictionary, if not create MediaPlayer and Relay, then add to Dictionary, then return as object
        
        playerTrack = 'None'
        dockerIp = str(dockerIp)
        
        asyncio.set_event_loop(self.loop)
        
        print("DEBUG, PRINT THREAD LOOP ID")
        print(id(self.loop))
        
            
        if dockerIp in self.playerCamDictionary:
            print("Player exists, return new relays")
            # Get player from dict array
            player = self.playerCamDictionary[dockerIp]
                
            # Get desired player track    
            if audioOrVideo == 'audio':
                returnTrack = self.relay.subscribe(((self.playerCamDictionary[dockerIp]).audio), buffered=False)
            elif audioOrVideo == 'video':
                returnTrack = self.relay.subscribe(((self.playerCamDictionary[dockerIp]).video), buffered=False)

            try:
                # Try to get existing array, and modify
                relayArray = self.uuidRelays[uuid]
                
            except Exception as e:
                print(e)
                
            relayArray.append(returnTrack)
        
            self.uuidRelays[uuid] = relayArray
            
            # Return Media Track
            return returnTrack
        else:
            print("Create player, return new relays")
            # No player
            # Create player
            asyncio.set_event_loop(self.loop)
            player = MediaPlayer("rtsp://" + dockerIp + ":8554/cam1", options={'hwaccel': 'auto'})
            
            # Add to dictionaries
            self.playerCamDictionary[dockerIp] = player
            
            # relay = MediaRelay()
            
            if audioOrVideo == 'audio':
                returnTrack = self.relay.subscribe(((self.playerCamDictionary[dockerIp]).audio), buffered=False)
            elif audioOrVideo == 'video':
                returnTrack = self.relay.subscribe(((self.playerCamDictionary[dockerIp]).video), buffered=False)

            relayArray = []                

            print("MADE")
            # Add relay to UUID array
            try:
                # Try to get existing array
                relayArray = (self.uuidRelays[uuid])
                
            except Exception as e:
                print(e)
                # Does not exist, create
                relayArray = []                
            
            # Add track to relayArray 
            relayArray.append(returnTrack)
        
            # Set perminantly
            self.uuidRelays[uuid] = relayArray
            
            # Return Media Player
            return returnTrack

    def run(self):
        self.loop.run_forever()
        
mediaThread = MediaPlayerPersistanceThread()
```

```
        # MediaPlayer Thread for objects to persist in
        mediaThreadRun = Thread(target=mediaThread.run)
        mediaThreadRun.start()
```

Then when I want to grab a Player object, I check if one exists, if so I return the wanted Track, if not I create a player and return the track, I invoke like so:

`audioRelay = mediaThread.returnTrack(dockerIP, 'audio', thisUUID)`

The issue comes when I finish my webRtc session, this ending the event loop I called the above code from. Somehow the MediaPlayer object get's attached to the temporary RTC loop I made for my WebRTC client, when I modified the library to make it the correct event loop to debug however, it fails with no obvious reason why, no verbosity.

My thinking is here that MediaPlayer, any Relays, and the Consumer NEEDS to be in the same event loop to work, but then why would MediaRelay even exist if that wasn't the idea? I want my players just grabbing the media and waiting for Relays to attach and detatch so my clients have a seemless experience and low server resource usage from just one MediaPlayer. but I'm not sure how that can be achieved. or if it's even possible.

**Comment by R0NAM1** [comment]
The exception I mentioned, 
```
/usr/lib/python3.11/asyncio/base_events.py:678: RuntimeWarning: coroutine 'Queue.put' was never awaited
  self._ready.clear()
Object allocated at (most recent call last):
  File "/home/r0nam1/Coding/zemond/python/venv/lib/python3.11/site-packages/aiortc/contrib/media.py", lineno 158
    asyncio.run_coroutine_threadsafe(video_track._queue.put(frame), loop)

<_UnixSelectorEventLoop running=False closed=True debug=True>

Running Threads After: 12

Exception in thread media-player:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/r0nam1/Coding/zemond/python/venv/lib/python3.11/site-packages/aiortc/contrib/media.py", line 158, in player_worker_decode
    asyncio.run_coroutine_threadsafe(video_track._queue.put(frame), loop)
  File "/usr/lib/python3.11/asyncio/tasks.py", line 926, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 806, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
/usr/lib/python3.11/threading.py:1040: RuntimeWarning: coroutine 'Queue.put' was never awaited
  self._invoke_excepthook(self)
Object allocated at (most recent call last):
  File "/home/r0nam1/Coding/zemond/python/venv/lib/python3.11/site-packages/aiortc/contrib/media.py", lineno 158
    asyncio.run_coroutine_threadsafe(video_track._queue.put(frame), loop)
```

I'm not sure why the loop is the RTCLoop anyways, as I did some interactive printing with the library and the media-player thread is only created ONCE my webrtc session starts, not when I add the transceiver, not when I return the answer SDP to the client, only when the client reaches out and starts webrtc does the player start what it does, which is not the wanted behavior at all. I can see some solution with MediaBlackhole and MediaRelay but I'm not sure how that would look.

**Comment by R0NAM1** [comment]
It seems like the RTCPeerConnection is the actual object requesting the frames, and MediaRelay IS just proxying not only the frames, but not even requesting and dumping frames when no other object IS requesting them like I thought, a custom implementation might fix this.
